by robertragas: add a white color for the badge-accent to increase re…
goalgorilla/open_social pull request #2063
Opened 2020-11-10 17:41 UTC by robertragas

…adability

## Problem
In the old theme the badge number was white on orange. Now in SKY it's black on orange. This makes is harder to read.

## Solution
Change the badge number to white.

## Issue tracker
*Paste a link to the drupal.org issue queue item. If any other issue trackers were used, include links to those too.*

## How to test
- [ ] Enable social_private_message
- [ ] Send a Private message to someone
- [ ] See the counter is black
- [ ] Check out to this branch
- [ ] See the counter is now white

## Screenshots
Before
![Screen Shot 2020-11-10 at 6 36 17 PM](https://user-images.githubusercontent.com/19951171/98710699-4da13d80-2384-11eb-8138-f0c7a7294bb0.png)

After
![Screen Shot 2020-11-10 at 6 36 24 PM](https://user-images.githubusercontent.com/19951171/98710720-53971e80-2384-11eb-9b2d-af7f28066a68.png)

## Release notes
We changed the badge number from black to white making it more readable.

2020-11-10 17:42 UTC, robertragas commented
To be honest. This came out of UAT of a client and was agreed to change the color. But now that I see this I think we should reconsider as the contrast of black on orange is a lot better.

![Screen Shot 2020-11-10 at 6 37 31 PM](https://user-images.githubusercontent.com/19951171/98710832-76293780-2384-11eb-8605-b7d8998a508a.png)
![Screen Shot 2020-11-10 at 6 37 21 PM](https://user-images.githubusercontent.com/19951171/98710839-77f2fb00-2384-11eb-9152-46db977ed7ea.png)

2020-11-24 09:11 UTC, jochemvn requested changes
You've now set the number to fixed white. This introduces problems for the default Open Social badge, since that's now an unreadable white on yellow... Also other platform might get into trouble. See attached screenshots.

![Screenshot 2020-11-24 at 10 06 33](https://user-images.githubusercontent.com/16667744/100073090-57737800-2e3d-11eb-9194-c827f4a0559f.png)
![Screenshot 2020-11-24 at 10 08 29](https://user-images.githubusercontent.com/16667744/100073092-580c0e80-2e3d-11eb-9bf2-dd444b9957d3.png)

2020-12-01 21:44 UTC, robertragas commented
> You've now set the number to fixed white. This introduces problems for the default Open Social badge, since that's now an unreadable white on yellow... Also other platform might get into trouble. See attached screenshots.
> 
> ![Screenshot 2020-11-24 at 10 06 33](https://user-images.githubusercontent.com/16667744/100073090-57737800-2e3d-11eb-9194-c827f4a0559f.png)
> ![Screenshot 2020-11-24 at 10 08 29](https://user-images.githubusercontent.com/16667744/100073092-580c0e80-2e3d-11eb-9bf2-dd444b9957d3.png)

I made it a bit more flexible by adding a new color to the theme, where you can change the accent color text. This way everyone can be happy, by default I keep it "4d4d4d" like it was before.

2020-12-14 13:59 UTC, jochemvn approved these changes

2020-12-14 19:23 UTC, merged