Issue #3207791 by rolki: Implement basic comment querying in the Graph
goalgorilla/open_social pull request #2285
Opened 2021-04-08 12:56 UTC by rollki

## Problem
*Describe the problem you're trying to solve, this should motivate why the changes you're proposing are needed.*

## Solution
*Describe the solution you've created, elaborate on any technical choices you've made. Why is this the right solution and is a different solution not the right one?*

## Issue tracker
*Paste a link to the drupal.org issue queue item. If any other issue trackers were used, include links to those too.*

## How to test
*For example*
- [ ] Using version X.Y.Z of Open Social with the example module enabled
- [ ] As a sitemanager
- [ ] Try to enable the option B on screen c/d/e
- [ ] When saving I expect the result to be F but instead see G.
- [ ] The expected result F is attained when repeating the steps with this fix applied.

## Screenshots
*If this Pull Request makes visual changes then please include some screenshots that show what has changed here. A before and after screenshot helps the reviewer determine what changes were made.*

## Release notes
*A short summary of the changes that were made that can be included in release notes.*

## Change Record
*If this Pull Request changes the way that developers should do things or introduces a new API for developers then a change record to document this is needed. Please provide a draft for a change record or a link to an unpublished change record below. [Existing change records](https://www.drupal.org/list-changes/social) can be consulted as example.*

## Translations
*Translatable strings are always extracted from the latest development branch. To ensure translations remain available for platforms running older versions of Open Social the original string should be added to `translations.php` when it's changed or removed.*
- [ ] Changed or removed source strings are added to the `translations.php` file.

2021-04-12 13:03 UTC, Kingdutch requested changes
Hey Roman,

I think it's an okay first proposal but we need to tidy up some things. We also need to look at the schema for comments and files itself. I've added some thoughts in comments but some more below.

One thing that's missing from the comment schema is how we deal with threading/replies. If I'm fetching a comment, how do I know what it was in reply to and how do I know what replies it has? I think we should also discuss this with @ronaldtebrake. For example should a comment provide a direct path to the content it belongs to or would it be acceptable to have `comment.parent.parent` to reach the non-comment content.

Additionally we currently have some text for a comment but we don't know information like `author` and the date on which it was updated/created. Which are probably things we want to display.

We can't add any GraphQL functionality without it being accompanied by tests (this is the case for both distro and non-distro work). You can look at the chat for an example and some helpers exist to test your pagination implementations. If you need help with what to test or how to test, please let me know.

~ Alexander

2021-04-13 15:34 UTC, rollki commented on modules/social_features/social_comment/graphql/open_social_comment.base.graphqls
> +  The Universally Unique Identifier for the discussion entity.
Changed.

2021-04-13 15:36 UTC, rollki commented on modules/social_features/social_comment/graphql/open_social_comment.base.graphqls
> +  message: String!
Used `body` for now but we should think about your proposal [here](https://opensocial.slack.com/archives/C01BYJCF4F4/p1618239500009900)

2021-04-13 15:37 UTC, rollki commented on modules/social_features/social_comment/graphql/open_social_comment.base.graphqls
> +    reverse: Boolean = false
Added

2021-04-13 15:38 UTC, rollki commented on modules/social_features/social_comment/graphql/open_social_comment.base.graphqls
> +    sortKey: UserSortKeys = CREATED_AT
Agree 🙈
Added `AttachmentSortKeys`, but also not sure if it a good idea to add the ability to sort attachments, so maybe we can use default sorting.

2021-04-23 16:16 UTC, Kingdutch commented
This needs some more tests, most notably to check that access handling is correctly implemented (and doesn't regress in the future) :)

2021-04-26 10:31 UTC, Kingdutch commented
The added tests demonstrate that access checks for the CommentQueryHelper are not sufficient. Doing this after fetching from the database isn't an option as it breaks our pagination.

A proposed implementation for a fix is written in https://www.drupal.org/project/social/issues/3210685 which should be created as a separate PR before this can be merged.

2021-05-25 15:31 UTC, Kingdutch approved these changes
Forced push a cleanup of all the "fix" commits so its easier to spot what work belongs together.

This now seems to adhere to the requirements of the story so if the tests pass then this can be merged.

2021-05-26 10:47 UTC, merged