update search_api to latest version to allow usage of current solr submodule
goalgorilla/open_social pull request #2307
Opened 2021-04-29 08:20 UTC by slowflyer

## Problem
With current version 1.15 of search_api it is not possible to use suggested or latest version of the solr submodule.

## Solution
Update to search_api 1.19

## Issue tracker
https://www.drupal.org/project/social/issues/3171966

## How to test
Check serach configuration and use search function on your install

2021-05-03 13:45 UTC, Kingdutch requested changes
Thanks so far @slowflyer ! Looks like a good improvement. We may be able to get rid of even more code and probably need to update our install config for good measure :) 

Based on a look at the Search API release notes this needs a bit of work: https://www.drupal.org/project/social/issues/3171966#comment-14090657

We also may need to include some of the things from the Search API release notes in our own release notes (see my comment on the issue).

2021-05-06 07:44 UTC, slowflyer commented
After some testing yesterday evening, I'm convinced that **_social_search_retrigger_profile** and **social_search_user_update** can be removed, and I removed both functions. 
Creating a new user, blocking a user, enabling a user and updating user profile works fine without.

After having a short look at **social_search_resave_search_indexes** which is only called form social_tagging.install, it seems that this can be removes as well. But want to have a second opinion on this.

2021-05-07 07:24 UTC, slowflyer commented
I guess, I need a hint, why this Travis error occurs:

--- Failed scenarios:
    /var/www/html/profiles/contrib/social/tests/behat/features/capabilities/private-message/create-private-message.feature:8

No idea, how this is related to search api.

2021-05-07 07:27 UTC, ronaldtebrake commented
Hi @slowflyer its usually a false negative, we will have to see if we can stabilize that one as it indeed doesn't seem to be related to your work. I'll restart the test to see if we can get it passed.

Thanks for all your hard work!!

2021-05-08 12:19 UTC, ronaldtebrake commented on modules/social_features/social_search/config/install/search_api.index.social_all.yml
> +          flexible_group: teaser
flexible/secret are optional modules, most likely it's enabled in your environment but we shouldn't have it in here as they might be disabled for the users.

2021-05-17 10:32 UTC, navneet0693 approved these changes

2021-05-17 10:43 UTC, merged