Issue #3216573 by tBKoT: Fix notification issue for follow tag activity
goalgorilla/open_social pull request #2365
Opened 2021-05-31 14:38 UTC by dmytriikaiun

## Problem
*Describe the problem you're trying to solve, this should motivate why the changes you're proposing are needed.*

## Solution
*Describe the solution you've created, elaborate on any technical choices you've made. Why is this the right solution and is a different solution not the right one?*

## Issue tracker
*Paste a link to the drupal.org issue queue item. If any other issue trackers were used, include links to those too.*

## How to test
*For example*
- [ ] Using version X.Y.Z of Open Social with the example module enabled
- [ ] As a sitemanager
- [ ] Try to enable the option B on screen c/d/e
- [ ] When saving I expect the result to be F but instead see G.
- [ ] The expected result F is attained when repeating the steps with this fix applied.

## Screenshots
*If this Pull Request makes visual changes then please include some screenshots that show what has changed here. A before and after screenshot helps the reviewer determine what changes were made.*

## Release notes
*A short summary of the changes that were made that can be included in release notes.*

## Change Record
*If this Pull Request changes the way that developers should do things or introduces a new API for developers then a change record to document this is needed. Please provide a draft for a change record or a link to an unpublished change record below. [Existing change records](https://www.drupal.org/list-changes/social) can be consulted as example.*

## Translations
*Translatable strings are always extracted from the latest development branch. To ensure translations remain available for platforms running older versions of Open Social the original string should be added to `translations.php` when it's changed or removed.*
- [ ] Changed or removed source strings are added to the `translations.php` file.

2021-06-04 10:01 UTC, ribel approved these changes

2021-06-04 10:18 UTC, ribel requested changes
@dmytriikaiun Changes looks good to me, as we discussed.
But I see we don't have any tests for this functionality, so would be good to add it.

2021-06-09 12:32 UTC, Kingdutch commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2365-wd9weoddywtm1ed5tpha2pi0i4b7d0gc.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c0b2f4757146cd20a11c3b

2021-06-14 06:52 UTC, ribel approved these changes

2021-06-14 06:53 UTC, merged