Issue #3219417 by SV: Add translation support for Topic content type
goalgorilla/open_social pull request #2387
Opened 2021-06-18 09:54 UTC by volodymyr-sydor-lemberg

## Problem
As a CM+ I want to be able to add Topics in multiple languages

## Solution
Enable translation for Topic content type and all relevant fields

## Issue tracker
- https://www.drupal.org/project/social/issues/3219417
- https://getopensocial.atlassian.net/browse/YANG-5701

## How to test
*For example*
- [ ] Using the latest version of Open Social with the social_topic module enabled
- [ ]  Login as an admin
- [ ]  Make sure you have at least two languages installed
- [ ]  Add an "Topic" and attach it to any group
- [ ]  Add translation for the created topic
- [ ]  Visit pages with the topic

## Release notes
 Add translation compatibility for Topic node type.

2021-06-18 10:00 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2387-cucch6mitst2f7bwnpjn9fgxr8p5exax.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60cc6d43c17bbe5a057c40d6

2021-06-22 14:44 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2387-cucch6mitst2f7bwnpjn9fgxr8p5exax.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60cc6d43c17bbe5a057c40d6

2021-06-22 16:01 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2387-cucch6mitst2f7bwnpjn9fgxr8p5exax.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60cc6d43c17bbe5a057c40d6

2021-06-25 16:08 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2387-cucch6mitst2f7bwnpjn9fgxr8p5exax.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60cc6d43c17bbe5a057c40d6

2021-07-06 13:54 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2387-cucch6mitst2f7bwnpjn9fgxr8p5exax.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60cc6d43c17bbe5a057c40d6

2021-07-07 20:37 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2387-cucch6mitst2f7bwnpjn9fgxr8p5exax.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60cc6d43c17bbe5a057c40d6

2021-07-12 08:41 UTC, volodymyr-sydor-lemberg commented on modules/social_features/social_topic/config/update/social_topic_update_8910.yml
> +              default_langcode:
Looks like duplicated, removed it

2021-07-12 08:42 UTC, volodymyr-sydor-lemberg commented on modules/social_features/social_topic/config/update/social_topic_update_8910.yml
> +              default_langcode:
removed it too

2021-07-12 13:49 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2387-cucch6mitst2f7bwnpjn9fgxr8p5exax.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60cc6d43c17bbe5a057c40d6

2021-07-12 14:02 UTC, ribel requested changes

2021-07-12 14:18 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2387-cucch6mitst2f7bwnpjn9fgxr8p5exax.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60cc6d43c17bbe5a057c40d6

2021-07-13 15:43 UTC, volodymyr-sydor-lemberg commented on modules/social_features/social_topic/social_topic.install
> +function social_topic_update_8910() {
done

2021-07-13 16:06 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2387-cucch6mitst2f7bwnpjn9fgxr8p5exax.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60cc6d43c17bbe5a057c40d6

2021-07-13 21:06 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2387-cucch6mitst2f7bwnpjn9fgxr8p5exax.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60cc6d43c17bbe5a057c40d6

2021-07-13 21:52 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2387-cucch6mitst2f7bwnpjn9fgxr8p5exax.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60cc6d43c17bbe5a057c40d6

2021-07-14 08:49 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2387-cucch6mitst2f7bwnpjn9fgxr8p5exax.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60cc6d43c17bbe5a057c40d6

2021-07-14 09:30 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2387-cucch6mitst2f7bwnpjn9fgxr8p5exax.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60cc6d43c17bbe5a057c40d6

2021-07-14 09:47 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2387-cucch6mitst2f7bwnpjn9fgxr8p5exax.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60cc6d43c17bbe5a057c40d6

2021-07-14 09:56 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2387-cucch6mitst2f7bwnpjn9fgxr8p5exax.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60cc6d43c17bbe5a057c40d6

2021-07-14 09:57 UTC, ribel approved these changes

2021-07-14 09:58 UTC, merged