Issue #3224886 by tBKoT: Add redirect for the group home page
goalgorilla/open_social pull request #2433
Opened 2021-07-22 12:52 UTC by dmytriikaiun

## Problem
The `group/{group}/home` page is not used anywhere and it returns just a white page only with a title. That provides some issues with already existing aliases and users do not see any information on this page.

## Solution
Add the `social_group_default.group_home` route as one of those needs to be redirected to the group tab from group settings in the `social_group_default_route` module's `RedirectSubscriber`.

## Issue tracker
https://getopensocial.atlassian.net/browse/YANG-5837
https://www.drupal.org/project/social/issues/3224886

## How to test
- [ ] As a LU
- [ ] Go to the `group\{group}\home

## Screenshots
![зображення](https://user-images.githubusercontent.com/11648677/126641472-26603945-72eb-440f-9bf8-617bc2006f69.png)

## Release notes
Now all users that go to the group/{group_id}/home page will be redirected to the selected tab in group settings.

## Change Record
N/A

## Translations
N/A

2021-07-22 12:59 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2433-uz314odunzw7ugkdcoties0e5qcewrnt.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60f96a2200f236c3af1301f5

2021-07-27 08:34 UTC, ribel requested changes
I tested that before it was possible to set clean alias like test-alias which then redirects to Group Stream or About, for example here: https://eci.getopensocial.net/test-alias

With the changes you made this is not possible anymore: https://pr2433-uz314odunzw7ugkdcoties0e5qcewrnt.tugboat.qa/test-alias

2021-07-29 06:21 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2433-uz314odunzw7ugkdcoties0e5qcewrnt.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60f96a2200f236c3af1301f5

2021-07-29 07:07 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2433-uz314odunzw7ugkdcoties0e5qcewrnt.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60f96a2200f236c3af1301f5

2021-08-04 11:17 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2433-uz314odunzw7ugkdcoties0e5qcewrnt.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60f96a2200f236c3af1301f5

2021-08-06 13:34 UTC, ribel approved these changes

2021-08-06 13:37 UTC, merged

2021-08-06 13:41 UTC, ribel commented
🍒 picked to 10.2.x, 10.1.x and 10.0.x