Issue #3225997 by rolki: As a user I want to be able to share a post
goalgorilla/open_social pull request #2447
Opened 2021-07-30 08:39 UTC by rollki

## Problem
*Describe the problem you're trying to solve, this should motivate why the changes you're proposing are needed.*

## Solution
*Describe the solution you've created, elaborate on any technical choices you've made. Why is this the right solution and is a different solution not the right one?*

## Issue tracker
*Paste a link to the drupal.org issue queue item. If any other issue trackers were used, include links to those too.*

## How to test
*For example*
- [ ] Using version X.Y.Z of Open Social with the example module enabled
- [ ] As a sitemanager
- [ ] Try to enable the option B on screen c/d/e
- [ ] When saving I expect the result to be F but instead see G.
- [ ] The expected result F is attained when repeating the steps with this fix applied.

## Screenshots
*If this Pull Request makes visual changes then please include some screenshots that show what has changed here. A before and after screenshot helps the reviewer determine what changes were made.*

## Release notes
*A short summary of the changes that were made that can be included in release notes.*

## Change Record
*If this Pull Request changes the way that developers should do things or introduces a new API for developers then a change record to document this is needed. Please provide a draft for a change record or a link to an unpublished change record below. [Existing change records](https://www.drupal.org/list-changes/social) can be consulted as example.*

## Translations
*Translatable strings are always extracted from the latest development branch. To ensure translations remain available for platforms running older versions of Open Social the original string should be added to `translations.php` when it's changed or removed.*
- [ ] Changed or removed source strings are added to the `translations.php` file.

2021-07-30 08:56 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2447-qkcfp8a0l5njgtzyeusll9i8bny4mxnp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6103bab9b52cf9584aaed80f

2021-07-30 10:07 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2447-qkcfp8a0l5njgtzyeusll9i8bny4mxnp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6103bab9b52cf9584aaed80f

2021-08-02 14:10 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2447-qkcfp8a0l5njgtzyeusll9i8bny4mxnp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6103bab9b52cf9584aaed80f

2021-08-09 10:04 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2447-qkcfp8a0l5njgtzyeusll9i8bny4mxnp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6103bab9b52cf9584aaed80f

2021-08-09 13:20 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2447-qkcfp8a0l5njgtzyeusll9i8bny4mxnp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6103bab9b52cf9584aaed80f

2021-08-11 13:13 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2447-qkcfp8a0l5njgtzyeusll9i8bny4mxnp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6103bab9b52cf9584aaed80f

2021-08-11 13:45 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2447-qkcfp8a0l5njgtzyeusll9i8bny4mxnp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6103bab9b52cf9584aaed80f

2021-08-11 14:47 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2447-qkcfp8a0l5njgtzyeusll9i8bny4mxnp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6103bab9b52cf9584aaed80f

2021-08-12 09:32 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2447-qkcfp8a0l5njgtzyeusll9i8bny4mxnp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6103bab9b52cf9584aaed80f

2021-08-12 10:52 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2447-qkcfp8a0l5njgtzyeusll9i8bny4mxnp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6103bab9b52cf9584aaed80f

2021-08-16 12:38 UTC, ribel requested changes

2021-08-16 12:38 UTC, ribel commented on modules/social_features/social_sharing/modules/social_sharing_post/templates/post-sharing.html.twig
> +  {% set facebook_url = 'https://www.facebook.com/share.php?u=' %}
I think we need to use methods of Shariff library or other third-party tools that we already use in Open Social for share buttons rather than re-create custom ones because it will be hard to support both.
But since this request was for PoC, let's wait on other feedback and future plans on this.

2022-02-02 07:57 UTC, ribel commented
Hi @rollki!
I know this PR was made as a PoC, so wondering if we should still keep it or maybe we can close? 
We can reopen it or create a new one when we will continue work on this feature.

2022-02-28 10:55 UTC, ribel commented
Discussed this with @rollki and closing for now. Can be re-opened if needed.

2022-02-28 10:55 UTC, closed without merging