Rever dublicate functionality
goalgorilla/open_social pull request #2489
Opened 2021-09-08 13:27 UTC by dmytriikaiun

## Problem
*Describe the problem you're trying to solve, this should motivate why the changes you're proposing are needed.*

## Solution
*Describe the solution you've created, elaborate on any technical choices you've made. Why is this the right solution and is a different solution not the right one?*

## Issue tracker
*Paste a link to the drupal.org issue queue item. If any other issue trackers were used, include links to those too.*

## How to test
*For example*
- [ ] Using version X.Y.Z of Open Social with the example module enabled
- [ ] As a sitemanager
- [ ] Try to enable the option B on screen c/d/e
- [ ] When saving I expect the result to be F but instead see G.
- [ ] The expected result F is attained when repeating the steps with this fix applied.

## Screenshots
*If this Pull Request makes visual changes then please include some screenshots that show what has changed here. A before and after screenshot helps the reviewer determine what changes were made.*

## Release notes
*A short summary of the changes that were made that can be included in release notes.*

## Change Record
*If this Pull Request changes the way that developers should do things or introduces a new API for developers then a change record to document this is needed. Please provide a draft for a change record or a link to an unpublished change record below. [Existing change records](https://www.drupal.org/list-changes/social) can be consulted as example.*

## Translations
*Translatable strings are always extracted from the latest development branch. To ensure translations remain available for platforms running older versions of Open Social the original string should be added to `translations.php` when it's changed or removed.*
- [ ] Changed or removed source strings are added to the `translations.php` file.

2021-09-08 13:34 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2489-xyr74mnet6vubt3u4fkbiizhwjmgg3jk.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6138ba5b08cf4761a96001bb

2021-09-10 14:22 UTC, ribel requested changes
@dmytriikaiun 
Please check the failing tests and fix update hooks.

2021-09-10 14:22 UTC, ribel commented on modules/social_features/social_event/social_event.install
> -function social_event_update_8916() {
We can't just remove update hooks that were released before.
You can remove the body of the update hook if it is deprecated, but leave a clear comment on what was done. 
See an example in `social_core_update_10102()`

2021-09-10 14:22 UTC, ribel commented on modules/social_features/social_event/social_event.install
> + * Update event values.
We already have released an update hook with a bigger number: `social_event_update_10201`.
It means this update hook will never be run on sites that use OS 10.2.x and later.
I think we need to add this PR to the 10.3 milestone. It means you can use update hooks bigger than `social_event_update_10304`.

2021-09-10 14:26 UTC, ribel commented
@dmytriikaiun Also please:

1. Create a drupal.org issue
2. Create drupal.org change record
3. Update How to test (label and behaviour is different)

2021-09-14 16:03 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2489-xyr74mnet6vubt3u4fkbiizhwjmgg3jk.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6138ba5b08cf4761a96001bb

2021-09-15 12:14 UTC, ribel approved these changes

2021-09-15 12:19 UTC, ribel commented
@dmytriikaiun Thanks for the fixes, but I still see failing test related to the update hook:

```
Error: Call to a member function getValue() on null in social_event_update_10305() (line 1950 of /var/www/html/profiles/contrib/social/modules/social_features/social_event/social_event.install).
```

2021-09-17 07:35 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2489-xyr74mnet6vubt3u4fkbiizhwjmgg3jk.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6138ba5b08cf4761a96001bb

2021-09-20 09:22 UTC, ribel commented
@dmytriikaiun We need to fix (or maybe deprecate) `social_event_post_update_10301_enable_event_enrollment()`, because it fails on update scenario.

2021-09-20 11:12 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2489-xyr74mnet6vubt3u4fkbiizhwjmgg3jk.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6138ba5b08cf4761a96001bb

2021-09-21 11:16 UTC, navneet0693 commented
@dmytriikaiun Please resolve the merge conflict.

2021-09-21 14:27 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2489-xyr74mnet6vubt3u4fkbiizhwjmgg3jk.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6138ba5b08cf4761a96001bb

2021-09-23 11:31 UTC, navneet0693 approved these changes

2021-09-23 13:05 UTC, merged

2021-09-23 13:06 UTC, ribel commented
🍒 picked to 10.3.x