Issue #3250368 by rolki: Add the ability to alter conditions in CommentQueryAccessHandler class
goalgorilla/open_social pull request #2613
Opened 2021-11-19 14:13 UTC by rollki

## Problem
*Describe the problem you're trying to solve, this should motivate why the changes you're proposing are needed.*

## Solution
*Describe the solution you've created, elaborate on any technical choices you've made. Why is this the right solution and is a different solution not the right one?*

## Issue tracker
*Paste a link to the drupal.org issue queue item. If any other issue trackers were used, include links to those too.*

## How to test
*For example*
- [ ] Using version X.Y.Z of Open Social with the example module enabled
- [ ] As a sitemanager
- [ ] Try to enable the option B on screen c/d/e
- [ ] When saving I expect the result to be F but instead see G.
- [ ] The expected result F is attained when repeating the steps with this fix applied.

## Screenshots
*If this Pull Request makes visual changes then please include some screenshots that show what has changed here. A before and after screenshot helps the reviewer determine what changes were made.*

## Release notes
*A short summary of the changes that were made that can be included in release notes.*

## Change Record
*If this Pull Request changes the way that developers should do things or introduces a new API for developers then a change record to document this is needed. Please provide a draft for a change record or a link to an unpublished change record below. [Existing change records](https://www.drupal.org/list-changes/social) can be consulted as example.*

## Translations
*Translatable strings are always extracted from the latest development branch. To ensure translations remain available for platforms running older versions of Open Social the original string should be added to `translations.php` when it's changed or removed.*
- [ ] Changed or removed source strings are added to the `translations.php` file.

2021-11-19 14:26 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2613-mafgmvkhrwmsj8j7sp1jb0ui5w07t9vz.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6197b1f8908ae1285b5ea28a

2021-11-24 14:30 UTC, rollki commented
[See also discussion here](https://bitbucket.org/goalgorilla/comment_permission/pull-requests/6/yang-6671-fix-issue-with-wrong-permissions)

2021-11-26 11:38 UTC, ribel approved these changes
@rollki Changes here looks good to me.
But since @dmytriikaiun is currently working on a related issue, I would like to receive his approval as well and also see if it needs to be combined and merged together with some other improvements for comment visibility.

2021-11-30 08:45 UTC, dmytriikaiun approved these changes

2021-11-30 08:49 UTC, dmytriikaiun commented
@ribel this PR does not affect and is not necessary for my changes in the distro, but it needs for the [PR](https://bitbucket.org/goalgorilla/comment_permission/pull-requests/7) in the comment_permission module.

2021-11-30 08:53 UTC, rollki commented
Hey, @andriiholub, @navneet0693
What do you think about this change? Can we merge it to OS 11.0.0?

2021-11-30 11:49 UTC, Ressinel approved these changes

2021-12-02 10:21 UTC, Kingdutch requested changes
Hey @rollki ,

`QueryAccessHandlerBase` already implements such an alter hook (check line 91 and 92)
```
    // Allow other modules to modify the conditions before they are used.
    $event = new QueryAccessEvent($conditions, $operation, $account, $entity_type_id);
    $this->eventDispatcher->dispatch("entity.query_access", $event);
    $this->eventDispatcher->dispatch("entity.query_access.{$entity_type_id}", $event);
```

Why do those events (which is the standard for all QueryAccessHandlers, e.g. [the group module implements them too](https://git.drupalcode.org/project/group/-/blob/8.x-1.x/src/Entity/Access/QueryAccessHandlerBase.php#L90)) not solve the problem that we have?

My suggestion here would be to close this as "Won't fix" and use the `entity.query_access` or `entity.query_access.comment` events instead.

2021-12-08 13:26 UTC, rollki commented
Hi @Kingdutch 
Not sure how I missed that 🙈
You are right, I'll decline this PR.

2021-12-08 13:26 UTC, closed without merging