Issue #3252050 by nkoporec: Ajax error when exporting event enrollments
goalgorilla/open_social pull request #2631
Opened 2021-12-01 12:52 UTC by nkoporec

## Problem
When trying to export event enrolments an AJAX error occurs.

## Solution
The issue is that in UserExportPluginBase the method profileGetFieldValue is typed hinted to return a string, but that is not entirely true, because the field can be NULL. So we need to make sure we always return a string.

## Issue tracker
https://www.drupal.org/project/social/issues/3252050

## How to test
1. Install the social_event_enrollments_export and social_birthday
2. Go to event with enrollments
3. Export the enrollments

## Screenshots
*If this Pull Request makes visual changes then please include some screenshots that show what has changed here. A before and after screenshot helps the reviewer determine what changes were made.*

## Release notes
Fixed an issue with exporting event enrolments.

## Change Record
*If this Pull Request changes the way that developers should do things or introduces a new API for developers then a change record to document this is needed. Please provide a draft for a change record or a link to an unpublished change record below. [Existing change records](https://www.drupal.org/list-changes/social) can be consulted as example.*

## Translations
*Translatable strings are always extracted from the latest development branch. To ensure translations remain available for platforms running older versions of Open Social the original string should be added to `translations.php` when it's changed or removed.*
- [ ] Changed or removed source strings are added to the `translations.php` file.

2021-12-01 12:59 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2631-xcnl2hgmeoxchqzlvsebkjlyanb74frn.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a77010b880b2370a0eae05

2021-12-01 13:11 UTC, NickDaelemans commented
Looks good!

2021-12-01 13:12 UTC, NickDaelemans approved these changes

2021-12-08 15:53 UTC, NickDaelemans approved these changes

2021-12-29 09:23 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2631-xcnl2hgmeoxchqzlvsebkjlyanb74frn.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a77010b880b2370a0eae05

2021-12-29 10:34 UTC, Ressinel requested changes

2021-12-29 10:34 UTC, Ressinel commented on modules/social_features/social_event/modules/social_event_managers/src/Plugin/views/field/SocialEventManagersViewsBulkOperationsBulkForm.php
>          $name .= ' ';
If `field_last_name` is empty we will have a name with space on the right side. I'd recommend `trim` the name before return.

2021-12-29 13:17 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2631-xcnl2hgmeoxchqzlvsebkjlyanb74frn.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a77010b880b2370a0eae05

2021-12-29 13:55 UTC, Ressinel approved these changes

2021-12-29 14:00 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2631-xcnl2hgmeoxchqzlvsebkjlyanb74frn.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a77010b880b2370a0eae05

2021-12-30 12:12 UTC, merged