[Internal] Improved defensive checks.
goalgorilla/open_social pull request #2641
Opened 2021-12-08 10:24 UTC by navneet0693

## Problem
Have more defensive checks in ActivityDigestWorker.

## Solution
Improve defensive checks.

## Issue tracker
N.A

## How to test
- [ ] Queues should work normally.

## Screenshots
N.A

## Release notes
N.A

## Change Record
N.A

## Translations
N.A

2021-12-08 10:31 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2641-tt85jm6wbhpbvld5cwrydo0la06vrltd.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61b087c5821ec85cda0bd494

2021-12-09 10:39 UTC, bojanbogdanovic commented on modules/custom/activity_send/modules/activity_send_email/src/Plugin/QueueWorker/ActivityDigestWorker.php
> +          ($activity->getRelatedEntity()->access('view', $target) === FALSE)
@navneet0693 could you fix plz the inconsistent indentation on these statements?

2021-12-13 08:29 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2641-tt85jm6wbhpbvld5cwrydo0la06vrltd.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61b087c5821ec85cda0bd494

2021-12-13 09:05 UTC, Ressinel requested changes

2021-12-13 09:05 UTC, Ressinel commented on modules/custom/activity_send/modules/activity_send_email/src/Plugin/QueueWorker/ActivityDigestWorker.php
> +          ($activity->getRelatedEntity()->access('view', $target) === FALSE)) {
@navneet0693  Let's do the same code style as you added above:
```
if (($activity instanceof Activity) &&
  ($activity->getRelatedEntity() !== NULL) &&
  ($activity->getRelatedEntity()->access('view', $target) === FALSE)
) {
...
```
or
```
if (
  ($activity instanceof Activity) &&
  ($activity->getRelatedEntity() !== NULL) &&
  ($activity->getRelatedEntity()->access('view', $target) === FALSE)
) {
...
```

2021-12-13 09:36 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2641-tt85jm6wbhpbvld5cwrydo0la06vrltd.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61b087c5821ec85cda0bd494

2021-12-13 14:24 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2641-tt85jm6wbhpbvld5cwrydo0la06vrltd.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61b087c5821ec85cda0bd494

2021-12-14 07:35 UTC, Ressinel approved these changes
Looks good to me.

2021-12-14 07:47 UTC, merged

2021-12-14 07:50 UTC, navneet0693 commented
🍒 -picked to 10.3.x, 10.2.x and 10.1.x

2021-12-14 08:45 UTC, ronaldtebrake commented
Don't roget 11.0.x ;)

2021-12-14 08:47 UTC, navneet0693 commented
@ronaldtebrake Thanks for reminding me.