Feature/3257730 update translations
goalgorilla/open_social pull request #2685
Opened 2022-01-10 10:46 UTC by NickDaelemans

## Problem
A lot of strings inside the Social profile are not yet translatable.

## Solution
Wrapping all strings inside the t() function will make those strings translatable.

## Issue tracker
https://www.drupal.org/project/social/issues/3257730

## How to test
- [ ] Go to a page that has a non-translatable string (/all-groups for example, 'Join method')
- [ ] Look for that string in the interface translations
- [ ] You should find that string and be able to translate it
- [ ] See the translated string (might have to clear cache)

## Release notes
We made a bunch of strings translatable by wrapping them with the `t()` function. This means they are translatable now, but that does not mean that all strings are already translated.

2022-01-10 10:51 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2685-ia5b0ceyb5yxawxykteg1h02ao3fvisa.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61dc0e797499db652200dd7e

2022-01-10 13:24 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2685-ia5b0ceyb5yxawxykteg1h02ao3fvisa.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61dc0e797499db652200dd7e

2022-01-10 13:40 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2685-ia5b0ceyb5yxawxykteg1h02ao3fvisa.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61dc0e797499db652200dd7e

2022-01-19 10:40 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2685-ia5b0ceyb5yxawxykteg1h02ao3fvisa.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61dc0e797499db652200dd7e

2022-02-02 07:53 UTC, ribel commented
Hi folks!
We also noticed that there are not-translatable strings, so I think it would be good to merge this one as soon as possible.

2022-02-02 07:53 UTC, ribel approved these changes

2022-02-02 08:29 UTC, Ressinel requested changes

2022-02-02 08:29 UTC, Ressinel commented on modules/custom/grequest/src/Plugin/GroupContentEnabler/GroupMembershipRequest.php
> +      'title' => t('Request group membership'),
Use `$this->t('Request group membership')`.

2022-02-02 08:29 UTC, Ressinel commented on modules/social_features/social_comment_upload/src/SocialCommentUploadConfigOverride.php
> +              'label' => t('Add attachment'),
Add `use StringTranslationTrait;` and use `$this->t('...')` in this file.

2022-02-02 08:29 UTC, Ressinel commented on modules/social_features/social_content_block/modules/social_event_content_block/src/Plugin/ContentBlock/EventContentBlock.php
> +        'label' => t('Event date'),
Add `use StringTranslationTrait;` and use `$this->t('...')` in this file.

2022-02-02 08:29 UTC, Ressinel commented on modules/social_features/social_content_block/src/ContentBlockBase.php
> +        'label' => t('Most recent'),
Add `use StringTranslationTrait;` and use `$this->t('...')` in this file.

2022-02-02 08:29 UTC, Ressinel commented on modules/social_features/social_group/modules/social_group_flexible_group/src/SocialGroupFlexibleGroupConfigOverride.php
> +        'label' => t('Join method'),
Add `use StringTranslationTrait;` and use `$this->t('...')` in this file.

2022-02-02 08:29 UTC, Ressinel commented on modules/social_features/social_group/modules/social_group_request/src/SocialGroupRequestConfigOverride.php
> +                  'label' => t('Message'),
Add `use StringTranslationTrait;` and use `$this->t('...')` in this file.

2022-02-02 08:29 UTC, Ressinel commented on modules/social_features/social_post/src/Entity/Post.php
> +        'label' => t('Community'),
Add `use StringTranslationTrait;` and use `$this->t('...')` in this file.

2022-02-02 08:29 UTC, Ressinel commented on modules/social_features/social_profile/modules/social_profile_fields/src/SocialProfileFieldsOverride.php
> +              'label' => t('Nickname'),
Add `use StringTranslationTrait;` and use `$this->t('...')` in this file.

2022-02-02 08:29 UTC, Ressinel commented on modules/social_features/social_tagging/src/SocialTaggingOverrides.php
> +          'label' => t('Tags'),
Add `use StringTranslationTrait;` and use `$this->t('...')` in this file.

2022-02-02 12:52 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2685-ia5b0ceyb5yxawxykteg1h02ao3fvisa.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61dc0e797499db652200dd7e

2022-02-02 12:59 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2685-ia5b0ceyb5yxawxykteg1h02ao3fvisa.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61dc0e797499db652200dd7e

2022-02-02 13:07 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2685-ia5b0ceyb5yxawxykteg1h02ao3fvisa.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61dc0e797499db652200dd7e

2022-02-02 13:13 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2685-ia5b0ceyb5yxawxykteg1h02ao3fvisa.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61dc0e797499db652200dd7e

2022-02-02 14:51 UTC, Ressinel approved these changes

2022-02-07 09:59 UTC, merged