Revoke select account cancellation method permission for authenticate…
goalgorilla/open_social pull request #2693
Opened 2022-01-17 09:33 UTC by NickDaelemans

…d users.

## Problem
If I disable my account as an authenticated user I have to choose a cancellation method when cancelling my own account.

## Solution
We should skip this step by removing the permissions for authenticated users. The desired cancellation method can be selected from within the user settings.

## Issue tracker
https://www.drupal.org/project/social/issues/3258883
## How to test
*For example*
- [ ] Log in as an authenticated user
- [ ] Cancel your account (Settings -> Cancel account)
- [ ] You should not be able to select a cancellation method.

## Release notes
By revoking the `select account cancellation method` authenticated users don't have to select a cancellation method anymore when cancelling their own account.

2022-01-17 09:39 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2693-ejsxggxanhxqisqkigfkbywbdzr0tuvb.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61e537f8f8a118577f2a4ebb

2022-01-17 09:50 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2693-ejsxggxanhxqisqkigfkbywbdzr0tuvb.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61e537f8f8a118577f2a4ebb

2022-01-19 08:49 UTC, nkoporec requested changes

2022-01-19 08:49 UTC, nkoporec commented on modules/social_features/social_user/social_user.install
> +}
Why duplicated update hook? If the intention here is to be backward compatible, then you should create a separate PR to 11.0.x and 10.3.x with the correct hook number.

2022-01-20 07:58 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2693-ejsxggxanhxqisqkigfkbywbdzr0tuvb.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61e537f8f8a118577f2a4ebb

2022-01-20 09:21 UTC, nkoporec approved these changes

2022-01-31 09:32 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2693-ejsxggxanhxqisqkigfkbywbdzr0tuvb.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61e537f8f8a118577f2a4ebb

2022-02-02 12:22 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2693-ejsxggxanhxqisqkigfkbywbdzr0tuvb.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61e537f8f8a118577f2a4ebb

2022-02-02 12:54 UTC, merged