Issue #3260416 by vnech: As a Logged-in User I should be able to follow another users
goalgorilla/open_social pull request #2712
Opened 2022-01-25 17:45 UTC by nechai

## Problem
As a LU User I should be able to follow another users. 

That means I should be able:

1. Follow any user
2. Unfollow any user

## Solution
- Add a new custom module allows follow/unfollow other users

## Issue tracker
- https://www.drupal.org/project/social/issues/3260416
- https://getopensocial.atlassian.net/browse/YANG-6955

## How to test
- [ ] Install the module `social_follow_user` 
- [ ] Login as LU
- [ ] Visit any public group members page (on user profile teasers you should see "Follow" button and be able "follow/unfollow" any user)
- [ ] Visit the profile page any user (you should see "Follow" button and be able "follow/unfollow" this user)

## Screenshots
N/A

## Release notes
*Make possible to"follow/unfollow" any user.*

## Change Record
N/A

## Translations
N/A

2022-01-25 17:50 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2712-wkqlsore5fnhjiy4wururdrefvlxev1j.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61f0372d046a4b8d29146ab9

2022-01-25 18:14 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2712-wkqlsore5fnhjiy4wururdrefvlxev1j.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61f0372d046a4b8d29146ab9

2022-02-21 09:39 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2712-wkqlsore5fnhjiy4wururdrefvlxev1j.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61f0372d046a4b8d29146ab9

2022-02-23 17:07 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2712-wkqlsore5fnhjiy4wururdrefvlxev1j.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61f0372d046a4b8d29146ab9

2022-03-10 09:13 UTC, rollki commented
LGTM.

2022-03-10 09:13 UTC, rollki approved these changes

2022-03-10 20:23 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2712-wkqlsore5fnhjiy4wururdrefvlxev1j.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61f0372d046a4b8d29146ab9

2022-03-10 20:55 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2712-wkqlsore5fnhjiy4wururdrefvlxev1j.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61f0372d046a4b8d29146ab9

2022-03-11 11:29 UTC, rollki commented on modules/social_features/social_follow_user/social_follow_user.install
> +  // Grant the default permissions for this feature.
It's can be more compact, e.g.:
```
$roles = [
'verified',
'contentmanager',
'sitemanager',
];

And foreach where you call `user_role_grant_permissions`
```

2022-03-11 11:31 UTC, rollki commented
@nechai There are one thing in code that we can change, please check it out.

2022-03-11 13:28 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2712-wkqlsore5fnhjiy4wururdrefvlxev1j.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61f0372d046a4b8d29146ab9

2022-03-11 14:13 UTC, rollki commented
LGTM, @OH17L Please  go ahead with your review here :)

2022-03-11 16:05 UTC, OH17L requested changes

2022-03-11 18:24 UTC, nechai commented on modules/social_features/social_follow_user/social_follow_user.info.yml
> +core_version_requirement: ^8.8 || ^9
fixed

2022-03-11 18:24 UTC, nechai commented on modules/social_features/social_follow_user/social_follow_user.info.yml
> +hidden: true
fixed

2022-03-11 18:24 UTC, nechai commented on modules/social_features/social_follow_user/social_follow_user.install
> + * Lifecycle functions for the "Social Follow User" module.
fixed

2022-03-11 18:24 UTC, nechai commented on modules/social_features/social_follow_user/social_follow_user.module
> +  return AccessResult::neutral();
fixed

2022-03-11 18:24 UTC, nechai commented on modules/social_features/social_follow_user/social_follow_user.install
> +    );
fixed

2022-03-11 18:24 UTC, nechai commented on modules/social_features/social_follow_user/social_follow_user.module
> +  if ($context['entity_type'] === 'profile' && !in_array($context['view_mode'], $allowed_display_modes)) {
fixed

2022-03-11 18:27 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2712-wkqlsore5fnhjiy4wururdrefvlxev1j.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61f0372d046a4b8d29146ab9

2022-03-14 11:58 UTC, ribel requested changes
@nechai 
All look good, but we need to fix few things before we can merge this:

1. Please make this module a hidden for now
2. Add more information to issue on d.org
3. Rebase commits

Thank you!

2022-03-14 12:48 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2712-wkqlsore5fnhjiy4wururdrefvlxev1j.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61f0372d046a4b8d29146ab9

2022-03-14 15:25 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2712-wkqlsore5fnhjiy4wururdrefvlxev1j.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61f0372d046a4b8d29146ab9

2022-03-14 15:46 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2712-wkqlsore5fnhjiy4wururdrefvlxev1j.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61f0372d046a4b8d29146ab9

2022-03-15 11:53 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2712-wkqlsore5fnhjiy4wururdrefvlxev1j.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61f0372d046a4b8d29146ab9

2022-03-16 10:38 UTC, ribel approved these changes
Now all look good, so I am going to merge this PR.
Thank you @nechai!

2022-03-16 10:40 UTC, merged