Issue #3260885 by tBKoT: New conent list block for multiple content types
goalgorilla/open_social pull request #2723
Opened 2022-01-28 13:29 UTC by dmytriikaiun

## Problem
As default, the custom content list block is allowed to select only one content type (topic, event, group, etc.) but CM+ should be able to select a multiple of them. However, if we just make content type selector multiple it could provide a lot of problems because every content type has its own query conditions.

## Solution
Create a new block that will provide the possibility to select multiple content types with fewer filter/sorting processes.

## Issue tracker
- https://getopensocial.atlassian.net/browse/YANG-6946
- https://www.drupal.org/project/social/issues/3260885

## How to test
- [ ] Using the latest version of Open Social with the `social_content_block_landing_page` module enabled
- [ ] As a CM+ create a Landing Page
- [ ] Add the `Custom multiple content list` section
- [ ] Set up content type and filter/sorting
- [ ] You should be able to see content list.

## Screenshots
#### Block configuration
![зображення](https://user-images.githubusercontent.com/11648677/151553570-337730a8-3095-491c-833e-1dcc9453d489.png)

#### Block display
![зображення](https://user-images.githubusercontent.com/11648677/151553715-a0b44882-462b-4d4b-8799-fdf6290c9742.png)

## Release notes
Now CM+ users could show a list of multiple content types.

## Change Record
To make it possible to use other content types you should provide a new `@MultipleContentBlock` plugin. 
The `entity_type` and `label` are required for correct work. 
To use only a specific bundle we should add a `bundle` in the annotation, in another case, all entities of the provided `entity_type` will be selected.

## Translations
N/A

2022-01-28 13:56 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2723-0eyzxu5r0d2sgpdeaf4xdqxybnnsuvsx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61f3f4d1046a4b8d294c43e4

2022-01-28 14:03 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2723-0eyzxu5r0d2sgpdeaf4xdqxybnnsuvsx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61f3f4d1046a4b8d294c43e4

2022-02-01 12:25 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2723-0eyzxu5r0d2sgpdeaf4xdqxybnnsuvsx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61f3f4d1046a4b8d294c43e4

2022-02-01 16:55 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2723-0eyzxu5r0d2sgpdeaf4xdqxybnnsuvsx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61f3f4d1046a4b8d294c43e4

2022-02-01 19:10 UTC, Ressinel requested changes

2022-02-01 19:10 UTC, Ressinel commented on modules/social_features/social_content_block/src/Plugin/Block/MultipleContentBlock.php
> +    // Sor by provided sorting field.
`Sor` -> `Sort`

2022-02-08 09:32 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2723-0eyzxu5r0d2sgpdeaf4xdqxybnnsuvsx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61f3f4d1046a4b8d294c43e4

2022-02-11 13:11 UTC, rollki commented on modules/social_features/social_content_block/src/Plugin/Block/MultipleContentBlock.php
> +        'created' => $this->t('Most resent'),
Most recent :)

2022-02-11 13:21 UTC, rollki commented on modules/social_features/social_content_block/src/Plugin/Block/MultipleContentBlock.php
> +      ${$type . '_storage'} = $this->entityTypeManager->getStorage($type);
:)

2022-02-11 13:23 UTC, rollki commented on modules/social_features/social_content_block/src/Plugin/Block/MultipleContentBlock.php
> +      $entity = ${$keys[0] . '_storage'}->load($keys[1]);
:)

2022-02-11 13:26 UTC, rollki commented on modules/social_features/social_content_block/src/Plugin/Block/MultipleContentBlock.php
> +  protected function getEntitiesByDefinitions(string $type, array $bundles = NULL): array {
```suggestion
  protected function getEntitiesByDefinitions(string $type, ?array $bundles): array {
```

2022-02-11 13:35 UTC, rollki requested changes
In general very good job, only few very small comments from me.

2022-02-14 09:23 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2723-0eyzxu5r0d2sgpdeaf4xdqxybnnsuvsx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61f3f4d1046a4b8d294c43e4

2022-02-14 09:35 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2723-0eyzxu5r0d2sgpdeaf4xdqxybnnsuvsx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61f3f4d1046a4b8d294c43e4

2022-02-14 14:29 UTC, Ressinel reviewed
Hi, @dmytriikaiun Code looks good to me! Nice work!

But I cannot add any content type except **Topic** [here](https://pr2723-0eyzxu5r0d2sgpdeaf4xdqxybnnsuvsx.tugboat.qa/node/24). There is a lot of different content on installation. Could you check this [Landing page](https://pr2723-0eyzxu5r0d2sgpdeaf4xdqxybnnsuvsx.tugboat.qa/node/24) and let me know if I do something wrong?

2022-02-17 11:57 UTC, dmytriikaiun commented
@Ressinel 
Yes, as default only Topics can be added all other content types are in submodules. I used the same behavior as for the `Custom content list block`

2022-02-17 12:26 UTC, rollki approved these changes
LGTM.

2022-02-17 12:47 UTC, Ressinel approved these changes

2022-02-28 12:05 UTC, rollki commented
Hi @dmytriikaiun 
Could you please rebase commits?  And then we will merge it.

2022-02-28 13:06 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2723-0eyzxu5r0d2sgpdeaf4xdqxybnnsuvsx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61f3f4d1046a4b8d294c43e4

2022-03-16 08:38 UTC, merged