by robertragas: add patch to move private message notifier to a submo…
goalgorilla/open_social pull request #2756
Opened 2022-02-08 15:51 UTC by robertragas

…dule and also add a check within OS

## Problem
*Describe the problem you're trying to solve, this should motivate why the changes you're proposing are needed.*

## Solution
*Describe the solution you've created, elaborate on any technical choices you've made. Why is this the right solution and is a different solution not the right one?*

## Issue tracker
*Paste a link to the drupal.org issue queue item. If any other issue trackers were used, include links to those too.*

## How to test
*For example*
- [ ] Using version X.Y.Z of Open Social with the example module enabled
- [ ] As a sitemanager
- [ ] Try to enable the option B on screen c/d/e
- [ ] When saving I expect the result to be F but instead see G.
- [ ] The expected result F is attained when repeating the steps with this fix applied.

## Screenshots
*If this Pull Request makes visual changes then please include some screenshots that show what has changed here. A before and after screenshot helps the reviewer determine what changes were made.*

## Release notes
*A short summary of the changes that were made that can be included in release notes.*

## Change Record
*If this Pull Request changes the way that developers should do things or introduces a new API for developers then a change record to document this is needed. Please provide a draft for a change record or a link to an unpublished change record below. [Existing change records](https://www.drupal.org/list-changes/social) can be consulted as example.*

## Translations
*Translatable strings are always extracted from the latest development branch. To ensure translations remain available for platforms running older versions of Open Social the original string should be added to `translations.php` when it's changed or removed.*
- [ ] Changed or removed source strings are added to the `translations.php` file.

2022-02-08 15:57 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2756-auzt9vllaakhkmtjopielj4hehpsctjj.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6202919200c7e8a7588eb8e5

2022-02-08 17:14 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2756-auzt9vllaakhkmtjopielj4hehpsctjj.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6202919200c7e8a7588eb8e5

2022-02-08 17:28 UTC, robertragas commented
@navneet0693 @tbsiqueira so this is the PR to fix the service not being found, but still needs a bit work, which I don't have time for tomorrow, but will check later.

So we use the patch which turns the private message notifier into a submodule, but in the submodule they actually change the method to contain 2 arguments instead of 3, and the one they removed $members is the one we actually alter. 

This has been moved to an alter hook, so think we don't actually need the service anymore but need to move it to the alter hook, that is, if we still want to use the patch.

2022-02-09 14:01 UTC, tbsiqueira commented on composer.json
> +                "Move message notify to a submodule so it doesn't crashes on update": "https://git.drupalcode.org/project/private_message/-/merge_requests/31.diff"
Hi Robert, Ronald made a comment to a [similar situation here](https://github.com/goalgorilla/open_social/pull/2748/files#r802637677) we should follow the same approach :D

2022-02-15 11:01 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2756-auzt9vllaakhkmtjopielj4hehpsctjj.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6202919200c7e8a7588eb8e5

2022-02-15 15:55 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2756-auzt9vllaakhkmtjopielj4hehpsctjj.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6202919200c7e8a7588eb8e5

2022-02-16 15:21 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2756-auzt9vllaakhkmtjopielj4hehpsctjj.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6202919200c7e8a7588eb8e5

2022-02-17 12:27 UTC, navneet0693 approved these changes

2022-02-17 12:28 UTC, navneet0693 requested changes
```

>  [notice] Update started: views_bulk_operations_update_8034
>  [notice] 1 view configs converted.
>  [notice] Update completed: views_bulk_operations_update_8034
>  [notice] Update started: social_user_export_update_11001
>  [notice] Update completed: social_user_export_update_11001
>  [notice] Update started: social_group_update_11001
> [info] Configuration views.view.groups has been successfully updated.
>  [notice] Update completed: social_group_update_11001
>  [notice] Update started: social_group_update_11002
>  [notice] Update completed: social_group_update_11002
>  [notice] Update started: social_group_update_11003
>  [notice] Update completed: social_group_update_11003
>  [notice] Update started: social_event_managers_update_11001
>  [notice] Update completed: social_event_managers_update_11001
>  [notice] Update started: social_event_enrolments_export_update_11001
>  [notice] Update completed: social_event_enrolments_export_update_11001
>  [notice] Update started: private_message_update_8007
>  [error]  Configuration objects (message.template.private_message_notification) provided by private_message_notify already exist in active configuration
>  [error]  Update failed: private_message_update_8007
>  [notice] Update started: social_event_an_enroll_update_11001
>  [notice] Update completed: social_event_an_enroll_update_11001
 [error]  Update aborted by: private_message_update_8007
 [error]  Finished performing updates.

```

2022-02-17 18:26 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2756-auzt9vllaakhkmtjopielj4hehpsctjj.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6202919200c7e8a7588eb8e5

2022-02-17 19:25 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2756-auzt9vllaakhkmtjopielj4hehpsctjj.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6202919200c7e8a7588eb8e5

2022-02-18 13:05 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2756-auzt9vllaakhkmtjopielj4hehpsctjj.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6202919200c7e8a7588eb8e5

2022-02-19 15:36 UTC, navneet0693 commented
@Ressinel https://www.drupal.org/project/private_message/issues/3029461 is now merged in 3.0.x branch.

2022-02-21 10:07 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2756-auzt9vllaakhkmtjopielj4hehpsctjj.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6202919200c7e8a7588eb8e5

2022-02-21 10:27 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2756-auzt9vllaakhkmtjopielj4hehpsctjj.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6202919200c7e8a7588eb8e5

2022-02-21 11:46 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2756-auzt9vllaakhkmtjopielj4hehpsctjj.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6202919200c7e8a7588eb8e5

2022-02-21 12:02 UTC, tbsiqueira approved these changes

2022-02-21 14:58 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2756-auzt9vllaakhkmtjopielj4hehpsctjj.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6202919200c7e8a7588eb8e5

2022-02-21 15:03 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2756-auzt9vllaakhkmtjopielj4hehpsctjj.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6202919200c7e8a7588eb8e5

2022-02-22 04:32 UTC, navneet0693 approved these changes

2022-02-22 04:33 UTC, merged

2022-02-22 04:38 UTC, navneet0693 commented
🍒 - picked to 11.0.x and 11.1.x