Issue #3268943 by SV: Add follow users lists.
goalgorilla/open_social pull request #2850
Opened 2022-04-01 09:59 UTC by volodymyr-sydor-lemberg

## Problem
*[Required] Describe the problem you're trying to solve, this should motivate why the changes you're proposing are needed.*

## Solution
*[Required] Describe the solution you've created, elaborate on any technical choices you've made. Why is this the right solution and is a different solution not the right one? What is the reasoning behind the chosen solution?*

## Issue tracker
*[Required] Paste a link to the drupal.org issue queue item. If any other issue trackers were used, include links to those too.*

## Theme issue tracker
*[Required if applicable] Paste a link to the drupal.org theme issue queue item, either from [socialbase](https://www.drupal.org/project/socialbase) or [socialblue](https://www.drupal.org/project/socialblue). If any other issue trackers were used, include links to those too.*

## How to test
*[Required] For example*
- [ ] Using version X.Y.Z of Open Social with the example module enabled
- [ ] As a sitemanager
- [ ] Try to enable the option B on screen c/d/e
- [ ] When saving I expect the result to be F but instead see G.
- [ ] The expected result F is attained when repeating the steps with this fix applied.

## Definition of done
### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] If applicable (I.E. new hook_updates) the update path from previous versions (major and minor versions) are tested
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
*[Required if new feature, and if applicable] If this Pull Request makes visual changes then please include some screenshots that show what has changed here. A before and after screenshot helps the reviewer determine what changes were made.*

## Release notes
*[Required if new feature, and if applicable] A short summary of the changes that were made that can be included in release notes.*

## Change Record
*[Required if applicable] If this Pull Request changes the way that developers should do things or introduces a new API for developers then a change record to document this is needed. Please provide a draft for a change record or a link to an unpublished change record below. Existing change records can be consulted as example. Please provide a draft for a change record or a link to an unpublished change record below. [Existing change records](https://www.drupal.org/list-changes/social) can be consulted as example.*

## Translations
*[Optional]Translatable strings are always extracted from the latest development branch. To ensure translations remain available for platforms running older versions of Open Social the original string should be added to `translations.php` when it's changed or removed.*
- [ ] Changed or removed source strings are added to the `translations.php` file.

2022-04-01 10:04 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2850-q4fkve0k0rllornm8roqxahl1c3vwdpb.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6246cd107dc9604ba3cb47ea

2022-04-01 10:09 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2850-q4fkve0k0rllornm8roqxahl1c3vwdpb.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6246cd107dc9604ba3cb47ea

2022-04-01 14:18 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2850-q4fkve0k0rllornm8roqxahl1c3vwdpb.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6246cd107dc9604ba3cb47ea

2022-04-04 07:38 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2850-q4fkve0k0rllornm8roqxahl1c3vwdpb.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6246cd107dc9604ba3cb47ea

2022-04-04 08:54 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2850-q4fkve0k0rllornm8roqxahl1c3vwdpb.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6246cd107dc9604ba3cb47ea

2022-04-04 16:38 UTC, OH17L requested changes
Add patches for themes to Composer's file and make improvements described below:

2022-04-04 16:38 UTC, OH17L commented on modules/social_features/social_profile/modules/social_profile_preview/src/Service/SocialProfilePreviewHelper.php
> +      $variables['#attached']['library'][] = 'social_follow_user/follow_user_btn';
Check if the social_follow_user module is enabled.

2022-04-04 16:38 UTC, OH17L commented on modules/social_features/social_profile/modules/social_profile_preview/templates/profile--profile--preview.html.twig
> +
```suggestion
  {% if content.followers or content.following %}
    <div class='follow-user--counter'>
      {{ content.followers }}
      {{ content.following }}
    </div>
  {% endif %}
  
  {{ content|without('field_profile_image', 'uid', 'flag_follow_user', 'private_message_link', 'field_profile_self_introduction', 'followers', 'following') }}
```

2022-04-04 16:38 UTC, OH17L commented on modules/social_features/social_follow_user/social_follow_user.module
> +      $build['social_following_user'] = [
Define the field in the "social_follow_user_entity_extra_field_info" hook and make the following changes:
```suggestion
    if ($display->getComponent('following') !== NULL) {
      $build['following'] = [
```

2022-04-04 16:38 UTC, OH17L commented on modules/social_features/social_follow_user/social_follow_user.libraries.yml
> +follow_user_btn:
```suggestion
button:
```

2022-04-04 16:38 UTC, OH17L commented on modules/social_features/social_follow_user/social_follow_user.libraries.yml
> +      assets/css/social_follow_user_btn.css: {}
```suggestion
      assets/css/social_follow_user.button.css: {}
```

2022-04-04 16:38 UTC, OH17L commented on modules/social_features/social_follow_user/social_follow_user.module
> +        $variables['social_follower'] = TRUE;
```suggestion
        $variables['followers'] = TRUE;
```

2022-04-04 16:38 UTC, OH17L commented on modules/social_features/social_follow_user/social_follow_user.module
> +        $variables['social_following'] = TRUE;
```suggestion
        $variables['following'] = TRUE;
```

2022-04-05 08:46 UTC, volodymyr-sydor-lemberg commented on modules/social_features/social_follow_user/config/install/views.view.following_users.yml
> +            authenticated: authenticated
I've found an existing one and would suggest using it: `flag follow_user`

2022-04-05 08:46 UTC, volodymyr-sydor-lemberg commented on modules/social_features/social_follow_user/config/install/views.view.followers_user.yml
> +            authenticated: authenticated
I've found an existing one and would suggest using it: `flag follow_user`

2022-04-05 11:23 UTC, volodymyr-sydor-lemberg commented on modules/social_features/social_follow_user/src/EventSubscriber/FlagEvents.php
> +      'following_user',
when one user click to follow/unfollow another then both counter should be "updated"

2022-04-05 17:04 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2850-q4fkve0k0rllornm8roqxahl1c3vwdpb.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6246cd107dc9604ba3cb47ea

2022-04-06 08:28 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2850-q4fkve0k0rllornm8roqxahl1c3vwdpb.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6246cd107dc9604ba3cb47ea

2022-04-06 18:43 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2850-q4fkve0k0rllornm8roqxahl1c3vwdpb.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6246cd107dc9604ba3cb47ea

2022-04-07 07:56 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2850-q4fkve0k0rllornm8roqxahl1c3vwdpb.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6246cd107dc9604ba3cb47ea

2022-04-07 14:12 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2850-q4fkve0k0rllornm8roqxahl1c3vwdpb.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6246cd107dc9604ba3cb47ea

2022-04-07 14:28 UTC, closed without merging

2022-04-08 08:05 UTC, OH17L commented
Replaced by PR #2867.