Issue #3272941: PHP warning for event enrollment listing (with no-enrollment)
goalgorilla/open_social pull request #2851
Opened 2022-04-01 12:41 UTC by nijuley

## Problem
Open Social showing PHP notice when I see the event enrollment list with no-enrollment

Trying to use values of type `null, bool, int, float or resource `as an array (such as `$null["key"]`) will now generate a notice.
`https://www.php.net/manual/en/migration74.incompatible.php#migration74.incompatible.core.non-array-access`

## Solution
`open_social\modules\social_features\social_event\modules\social_event_an_enroll_enrolments_export\src\SocialEventAnEnrollEnrolmentsExportOverrides.php:44`

`$overrides[$config_name]['display']['default']['display_options']['fields']['social_views_bulk_operations_bulk_form_enrollments_1']['selected_actions']['social_event_enrolments_export_enrollments_action'] = 0;`

Assigning a zero value and is not checking if the actions are actually there in the configuration or not, commenting that line will fix the warning

## Issue tracker
https://www.drupal.org/project/social/issues/3272941

## Theme issue tracker
N/A

## How to test
- [ ] On a fresh Installation or existing one,  enable `social_event` and `social_event_an_enroll_enrolments_export` module
- [ ] Create an event node and view all enrollment (node/{node}/all-enrollments)
- [ ] It will not show PHP notice

## Definition of done

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] If applicable (I.E. new hook_updates) the update path from previous versions (major and minor versions) are tested
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
Before
<img width="1195" alt="before" src="https://user-images.githubusercontent.com/4291466/161264182-4f8efec3-a590-4b6d-bc7f-bb1d72ba0ecc.png">
After

<img width="891" alt="after" src="https://user-images.githubusercontent.com/4291466/161265646-3ff4cace-07a1-4465-b7b6-9c0968ff66b5.png">

## Release notes
N/A

## Change Record
N/A

## Translations
N/A

2022-04-01 12:46 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2851-xjya9vnbecbvdbprxeo5zcxsu2zuqnv8.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6246f311d9027707d3dd3f00

2022-04-01 13:06 UTC, tbsiqueira requested changes

2022-04-01 13:06 UTC, tbsiqueira commented on modules/social_features/social_event/modules/social_event_an_enroll_enrolments_export/src/SocialEventAnEnrollEnrolmentsExportOverrides.php
> +//      $overrides[$config_name]['display']['default']['display_options']['fields']['social_views_bulk_operations_bulk_form_enrollments_1']['selected_actions']['social_event_enrolments_export_enrollm
Hi Nijuley, thank you for your work, you can safely remove this line ;)

2022-04-01 13:52 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2851-upskkx5ztwfg7ud8kfd6efaxg8kynapz.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/624702847dc9604ba3cc7d1b

2022-04-01 14:09 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2851-upskkx5ztwfg7ud8kfd6efaxg8kynapz.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/624702847dc9604ba3cc7d1b

2022-04-04 10:15 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2851-upskkx5ztwfg7ud8kfd6efaxg8kynapz.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/624702847dc9604ba3cc7d1b

2022-04-04 10:23 UTC, Ressinel approved these changes
Looks good to me.

2022-04-04 18:37 UTC, merged

2022-04-04 18:42 UTC, Ressinel commented
🍒-picked to `11.0.x`, `11.1.x`, and `11.2.x`