Issue #3273994 by agami4: Change color
goalgorilla/open_social pull request #2865
Opened 2022-04-07 13:02 UTC by agami4

## Problem
*[Required] Describe the problem you're trying to solve, this should motivate why the changes you're proposing are needed.*

## Solution
*[Required] Describe the solution you've created, elaborate on any technical choices you've made. Why is this the right solution and is a different solution not the right one? What is the reasoning behind the chosen solution?*

## Issue tracker
*[Required] Paste a link to the drupal.org issue queue item. If any other issue trackers were used, include links to those too.*

## Theme issue tracker
*[Required if applicable] Paste a link to the drupal.org theme issue queue item, either from [socialbase](https://www.drupal.org/project/socialbase) or [socialblue](https://www.drupal.org/project/socialblue). If any other issue trackers were used, include links to those too.*

## How to test
*[Required] For example*
- [ ] Using version X.Y.Z of Open Social with the example module enabled
- [ ] As a sitemanager
- [ ] Try to enable the option B on screen c/d/e
- [ ] When saving I expect the result to be F but instead see G.
- [ ] The expected result F is attained when repeating the steps with this fix applied.

## Definition of done
### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] If applicable (I.E. new hook_updates) the update path from previous versions (major and minor versions) are tested
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
*[Required if new feature, and if applicable] If this Pull Request makes visual changes then please include some screenshots that show what has changed here. A before and after screenshot helps the reviewer determine what changes were made.*

## Release notes
*[Required if new feature, and if applicable] A short summary of the changes that were made that can be included in release notes.*

## Change Record
*[Required if applicable] If this Pull Request changes the way that developers should do things or introduces a new API for developers then a change record to document this is needed. Please provide a draft for a change record or a link to an unpublished change record below. Existing change records can be consulted as example. Please provide a draft for a change record or a link to an unpublished change record below. [Existing change records](https://www.drupal.org/list-changes/social) can be consulted as example.*

## Translations
*[Optional]Translatable strings are always extracted from the latest development branch. To ensure translations remain available for platforms running older versions of Open Social the original string should be added to `translations.php` when it's changed or removed.*
- [ ] Changed or removed source strings are added to the `translations.php` file.

2022-04-07 14:41 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2865-8cbpao3xb5icahivkbipdz7tk5nhpqu7.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/624ee1017a1d6289544dc8f3

2022-04-18 08:21 UTC, Ressinel commented
Hi @agami4 

Could you prepare this PR fully to review since you added the label `needs review`?
Do I need to be assigned to this PR?

2022-04-22 14:19 UTC, Ressinel requested changes

2022-05-04 08:04 UTC, agami4 commented on modules/social_features/social_core/social_core.install
> +function social_core_update_11007(): void {
@Ressinel, done. Please check

2022-05-04 08:08 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2865-8cbpao3xb5icahivkbipdz7tk5nhpqu7.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/624ee1017a1d6289544dc8f3

2022-05-04 11:45 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2865-8cbpao3xb5icahivkbipdz7tk5nhpqu7.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/624ee1017a1d6289544dc8f3

2022-05-04 13:29 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2865-8cbpao3xb5icahivkbipdz7tk5nhpqu7.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/624ee1017a1d6289544dc8f3

2022-05-05 16:50 UTC, ribel approved these changes
Hi @agami4 and @Ressinel,
What is the status here?
For me, it looks like completed, but I think we will need to merge related theme changes to the 2.x branch and update the theme version here?

2022-05-05 19:37 UTC, Ressinel approved these changes

2022-05-05 19:41 UTC, Ressinel commented
@ribel Looks good to me as well.
We will merge related themes PRs to new dev branches 2.2.x and those theme changes will release with these changes in the distro. We will update the distro theme version right before the new distro release.

2022-05-05 19:43 UTC, Ressinel commented
@agami4 Could you remove redundant commits? And we will be ready to merge. Thanks!

2022-05-06 07:29 UTC, tbsiqueira commented
Hi @agami4, can you please add before and after screenshots with detailed information on what changed? This will be very important to add on our release notes. 

I would like to kindly as you to include the screenshots with all changes on this PR and d.org related ticket.

2022-05-10 07:08 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2865-8cbpao3xb5icahivkbipdz7tk5nhpqu7.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/624ee1017a1d6289544dc8f3

2022-05-10 09:06 UTC, agami4 commented
@Ressinel, @tbsiqueira, I've added screenshots(before, after) on the description. Please check.

2022-05-10 09:09 UTC, merged

2022-05-10 09:13 UTC, Ressinel commented
🍒-picked to `11.3.x`