Issue #3273988 by tBKoT: Shows titles corectly on the group invites page
goalgorilla/open_social pull request #2866
Opened 2022-04-07 13:28 UTC by tbkot

## Problem
When we invited a user to the group to which this user does not have access

## Solution
Create a new class for the `entity reference label` field formatted plugin

## Issue tracker
 - https://www.drupal.org/project/social/issues/3273988
 - https://getopensocial.atlassian.net/browse/YANG-7489

## Theme issue tracker
N/A

## How to test
- [x] Using the latest version of Open Social with the `social_group_invite` module enabled
- [x] As a CM+
- [x] Create a flexible group with the `Invite only` join method
- [x] Go to the Manage members page
- [x] Invite any user to this group
- [x] Log in as an invited user
- [x] Go to the `My invites` -> `Group invites`

## Definition of done
### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] If applicable (I.E. new hook_updates) the update path from previous versions (major and minor versions) are tested
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
![зображення](https://user-images.githubusercontent.com/11648677/162209702-aca10303-f83a-45e2-9c06-7c372d72188a.png)

## Release notes
Fixed issue when the user cannot see the group title on the group invites page

## Change Record
N/A

## Translations
N/A

2022-04-07 13:32 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2866-xljpbg3fumj71zfrxyd1xyyo1mbnyx5p.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/624ee6f0d9027707d3862922

2022-04-07 14:03 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2866-xljpbg3fumj71zfrxyd1xyyo1mbnyx5p.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/624ee6f0d9027707d3862922

2022-04-07 14:07 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2866-xljpbg3fumj71zfrxyd1xyyo1mbnyx5p.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/624ee6f0d9027707d3862922

2022-04-07 14:46 UTC, Ressinel requested changes
Looks good to me.

2022-04-08 08:22 UTC, dmytriikaiun commented on modules/social_features/social_group/modules/social_group_invite/social_group_invite.module
> +  if (isset($info['entity_reference_label'])) {
Added

2022-04-08 08:25 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2866-xljpbg3fumj71zfrxyd1xyyo1mbnyx5p.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/624ee6f0d9027707d3862922

2022-04-08 08:27 UTC, Ressinel approved these changes

2022-04-11 13:28 UTC, rollki approved these changes
LGTM.

2022-04-11 14:09 UTC, merged

2022-04-11 14:43 UTC, Ressinel commented
🍒-picked to [11.0.x](https://github.com/goalgorilla/open_social/commit/4f57d200ac8b6b07aaa31543248a493e8088c220), [11.1.x](https://github.com/goalgorilla/open_social/commit/6392c5f77e9bf9a2def3b7b6fce562e089e94faf), and [11.2.x](https://github.com/goalgorilla/open_social/commit/1c63ccaead257c29cd5d8d6f4a9958d6d4d4c9b2)