Issue #3201416 by hotwebmatter, DamienMcKenna, Ressinel: Spelling for "Notification Centre" should be American English
goalgorilla/open_social pull request #2880
Opened 2022-04-14 09:30 UTC by Ressinel

## Problem
The spelling of "Centre" should be "Center".

## Solution
Replace "Centre" with "Center" throughout all the Distro.

## Issue tracker
- https://www.drupal.org/project/social/issues/3201416

## Theme issue tracker
N/A

## How to test
- [ ] You should not see the word "Centre" on English site language anymore

## Definition of done
### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] If applicable (I.E. new hook_updates) the update path from previous versions (major and minor versions) are tested
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
The word "Centre" was replaced with "Center" throughout all the Open Social.

## Change Record
N/A

## Translations
N/A

2022-04-14 09:34 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2880-wt71oebqhsmx3jtt4gwliid1kbvstyn1.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6257e9d2492bf2bdb4de7da6

2022-06-01 08:11 UTC, tbsiqueira approved these changes

2022-06-01 08:12 UTC, tbsiqueira requested changes
Andrii, I'm not sure that .po files should be edited like this, that could generate an inconsistency between the translation platform and our files. I guess they should be edited directly on the tool, can you please revert them?

2022-06-02 04:53 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2880-zxjidldgirpfco71lkd1jguk0ohein90.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62974755ee0732728f708c0e

2022-06-21 11:27 UTC, navneet0693 approved these changes

2022-06-21 11:28 UTC, navneet0693 approved these changes

2022-06-21 11:29 UTC, merged

2022-06-21 11:31 UTC, navneet0693 commented
🍒 - picked to 11.4.x, 11.3.x, 11.2.x and 11.1.x