Issue #3277470 by SV: The "Followers" title is displayed on the followers page on Mobile
goalgorilla/open_social pull request #2909
Opened 2022-04-27 16:46 UTC by volodymyr-sydor-lemberg

## Problem
The "Followers" title is displayed above the user's avatar on the mobile site version:

![image-20220420-113754](https://user-images.githubusercontent.com/25609390/165571402-8a61c18f-c143-440a-9afd-b3090300aff8.png)

## Solution
The title should be removed in the related views

## Issue tracker
- https://www.drupal.org/project/social/issues/3277470
- https://getopensocial.atlassian.net/browse/YANG-7634

## How to test
- [ ] Using the latest version of Open Social with the social_follow_user module enabled
- [ ] As a LU try to open the followers page 
- [ ] When I switch to the mobile version I expect that there is no page title
- [ ] The expected result is attained when repeating the steps with this fix applied.

## Definition of done
### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] If applicable (I.E. new hook_updates) the update path from previous versions (major and minor versions) are tested
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
 Fixes a bug with displaying title on the followers page.

2022-04-28 09:01 UTC, OH17L requested changes

2022-04-28 15:34 UTC, volodymyr-sydor-lemberg commented on modules/social_features/social_follow_user/social_follow_user.install
> +function social_follow_user_update_11203(): void {
then lets switch to the related milestone

2022-05-03 11:07 UTC, open-social-tugboat commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2909-qfoilgyshkgfcvwibzztqmbuwqbz5uo0.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62710bd08a3b7b49de3d52f5

2022-05-03 14:23 UTC, OH17L approved these changes

2022-05-05 17:18 UTC, ribel commented
Hi @OH17L,
I see you approved this PR, but add `blocked: maitaner input` label without any comment or new assignee for review.
Since this is just a simple bugfix we can merge them by ourselves or if you are not sure - please add `optional review requested` and assign them to me or @Ressinel with a comment.

2022-05-06 04:51 UTC, Ressinel approved these changes
LGTM

2022-05-06 04:52 UTC, merged

2022-05-06 04:54 UTC, Ressinel commented
🍒-picked to `11.2.x`, and `11.3.x`