Issue #3280811 by vnech: Book page in Flexible Group
goalgorilla/open_social pull request #2931
Opened 2022-05-17 07:36 UTC by nechai

## Problem
There is no ability to add "Book page" nodes in "Flexible Group" groups.

## Solution
Add "Book page" node type as a group content to "Flexible Group" group type.

## Issue tracker
- https://www.drupal.org/project/social/issues/3280811

## Theme issue tracker
N/A

## How to test
- [ ] TBA

## Definition of done
### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] If applicable (I.E. new hook_updates) the update path from previous versions (major and minor versions) are tested
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
TBA

## Release notes
*Add possibility to have "Book page" node type in "Flexible Group"*

## Change Record
N/A

## Translations
N/A

2022-05-19 21:32 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2931-othcwflffm8fyfjcokialzqloqckc4ri.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6286b661a94aea8366d969e9

2022-05-19 21:50 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2931-othcwflffm8fyfjcokialzqloqckc4ri.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6286b661a94aea8366d969e9

2022-05-22 18:52 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2931-othcwflffm8fyfjcokialzqloqckc4ri.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6286b661a94aea8366d969e9

2022-05-22 21:47 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2931-othcwflffm8fyfjcokialzqloqckc4ri.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6286b661a94aea8366d969e9

2022-05-24 10:37 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2931-othcwflffm8fyfjcokialzqloqckc4ri.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6286b661a94aea8366d969e9

2022-05-25 19:41 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2931-othcwflffm8fyfjcokialzqloqckc4ri.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6286b661a94aea8366d969e9

2022-05-25 19:46 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2931-othcwflffm8fyfjcokialzqloqckc4ri.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6286b661a94aea8366d969e9

2022-05-25 19:53 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2931-othcwflffm8fyfjcokialzqloqckc4ri.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6286b661a94aea8366d969e9

2022-05-26 19:00 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2931-othcwflffm8fyfjcokialzqloqckc4ri.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6286b661a94aea8366d969e9

2022-06-03 09:17 UTC, rollki commented on modules/social_features/social_group/modules/social_group_flexible_group/modules/social_flexible_group_book/social_flexible_group_book.module
> +      // but due to this moment user gets "access denie" and previous route is
denied

2022-06-03 12:44 UTC, nechai commented on modules/social_features/social_group/modules/social_group_flexible_group/modules/social_flexible_group_book/config/install/views.view.group_books.yml
> +            'group_node:book': 'group_node:book'
Fixed

2022-06-03 12:44 UTC, nechai commented on modules/social_features/social_group/modules/social_group_flexible_group/modules/social_flexible_group_book/social_flexible_group_book.module
> +      // but due to this moment user gets "access denie" and previous route is
Fixed

2022-06-03 12:44 UTC, nechai commented
Hi @rollki ! Fixed, pls check.

2022-06-06 11:29 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2931-othcwflffm8fyfjcokialzqloqckc4ri.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6286b661a94aea8366d969e9

2022-06-06 12:42 UTC, rollki approved these changes
LGTM, let's wait for tests to be green.

2022-06-06 12:47 UTC, rollki commented
Hey @Ressinel 
Could you please take a look at this PR?

2022-06-07 09:52 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2931-othcwflffm8fyfjcokialzqloqckc4ri.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6286b661a94aea8366d969e9

2022-06-07 14:07 UTC, rollki commented
After adding notifications still LGTM :)

2022-06-08 13:13 UTC, Ressinel reviewed
Hi, @nechai I have some comments, see below, please.

1. There is no group name to which a book belongs and there is redundant left padding from the **Follow content** button.

![d82c2849e95cc12795c48d910536dfda](https://user-images.githubusercontent.com/10220937/172329289-017c0e67-f472-40f5-9d46-3b524a8abc97.png)

2. The **group manager** (he is only a verified user outside of the group) doesn't see the **Create book** button on the books overview page.

![c130db1df3840041ed2cddce6b956db6](https://user-images.githubusercontent.com/10220937/172622027-8a91c2cf-cfe4-45ca-a996-0b5d44dee8e7.png)
![d1be1f949a0b1d9be53a3ce2cf655ce8](https://user-images.githubusercontent.com/10220937/172622029-a9bd6b2b-7912-4aef-9c15-872db253fca0.png)


3. The **group manager** has access to create a Book page in Group (`/group/{gid}/content/create/group_node%3Abook`) but doesn't see the **Book outline** section.

![b521032e2dd05a297bb2a5c87db09b79](https://user-images.githubusercontent.com/10220937/172622271-ae24d8c4-6463-478f-a0fa-c45a555d7c57.png)

4. Book page creation notifications are not sent to group members. Can you add HTT for notifications?

2022-06-16 10:32 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2931-othcwflffm8fyfjcokialzqloqckc4ri.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6286b661a94aea8366d969e9

2022-06-17 14:23 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2931-othcwflffm8fyfjcokialzqloqckc4ri.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6286b661a94aea8366d969e9

2022-06-21 13:44 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2931-othcwflffm8fyfjcokialzqloqckc4ri.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6286b661a94aea8366d969e9

2022-06-21 14:09 UTC, nechai commented
Hi @Ressinel ! Regarding your [notices](https://github.com/goalgorilla/open_social/pull/2931#pullrequestreview-999715121):
1. For now we want to have some MVP version and this will be fixed later
2. Fixed in the [commit](https://github.com/goalgorilla/open_social/pull/2931/commits/45b470636f719961641e48d6b784f77af71f1de0)
3. Fixed in the [commit](https://github.com/goalgorilla/open_social/pull/2931/commits/45b470636f719961641e48d6b784f77af71f1de0)
4. I updated HTT section, please check

2022-06-22 08:47 UTC, Ressinel commented
Hi @nechai 

> 1. For now we want to have some MVP version and this will be fixed later

Then let's make this module experimental.

2022-06-22 14:33 UTC, nechai commented
Hi @Ressinel ! Marked the module as experimental

2022-06-22 14:37 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2931-othcwflffm8fyfjcokialzqloqckc4ri.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6286b661a94aea8366d969e9

2022-06-24 15:31 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2931-othcwflffm8fyfjcokialzqloqckc4ri.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6286b661a94aea8366d969e9

2022-06-27 12:20 UTC, Ressinel requested changes

2022-06-29 13:33 UTC, nechai commented on modules/social_features/social_group/modules/social_group_flexible_group/modules/social_flexible_group_book/social_flexible_group_book.info.yml
> +package: Social (Experimental)
Added

2022-06-29 13:33 UTC, nechai commented on modules/social_features/social_book/social_book.install
> +function social_book_update_11400(): string {
Fixed

2022-06-29 13:34 UTC, nechai commented on modules/social_features/social_group/modules/social_group_flexible_group/modules/social_flexible_group_book/social_flexible_group_book.install
> +  $install_helper = \Drupal::classResolver(SocialFlexibleGroupBookInstallHelper::class);
Moved to `.install `file

2022-06-29 13:34 UTC, nechai commented on modules/social_features/social_group/modules/social_group_flexible_group/modules/social_flexible_group_book/social_flexible_group_book.module
> +  ) {
Fixed

2022-06-29 13:34 UTC, nechai commented on modules/social_features/social_group/modules/social_group_flexible_group/modules/social_flexible_group_book/social_flexible_group_book.module
> +    /* @see \Drupal\social_group\SocialGroupSelectorWidgetConfigOverride::loadOverrides */
Fixed

2022-06-29 13:34 UTC, nechai commented on modules/social_features/social_group/modules/social_group_flexible_group/modules/social_flexible_group_book/social_flexible_group_book.module
> +  ) {
Fixed

2022-06-29 13:34 UTC, nechai commented on modules/social_features/social_group/modules/social_group_flexible_group/modules/social_flexible_group_book/social_flexible_group_book.module
> +
https://www.drupal.org/docs/develop/standards/coding-standards#controlstruct

2022-06-29 13:35 UTC, nechai commented on modules/social_features/social_group/modules/social_group_flexible_group/modules/social_flexible_group_book/social_flexible_group_book.module
> +  ) {
Fixed

2022-06-29 13:35 UTC, nechai commented on modules/social_features/social_group/modules/social_group_flexible_group/modules/social_flexible_group_book/social_flexible_group_book.module
> +    // @todo This should be added to the block configuration from here.
Removed redundant `@todo`

2022-06-30 12:22 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2931-othcwflffm8fyfjcokialzqloqckc4ri.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6286b661a94aea8366d969e9

2022-06-30 15:15 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2931-othcwflffm8fyfjcokialzqloqckc4ri.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6286b661a94aea8366d969e9

2022-07-01 11:01 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2931-othcwflffm8fyfjcokialzqloqckc4ri.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6286b661a94aea8366d969e9

2022-07-03 12:16 UTC, Ressinel approved these changes
LGTM

2022-07-03 12:16 UTC, merged

2022-07-03 12:21 UTC, Ressinel commented
🍒-picked to `11.4.x`