Issue #3284938 by alex.ksis: Move helper functions from album module to core.
goalgorilla/open_social pull request #2985
Opened 2022-06-09 19:08 UTC by ksis

## Problem
The Social Album has helper functions which install blocks on specified pages. The functions are: _social_album_blocks() and _social_album_install_blocks(). They are in the modules/social_features/social_album/social_album.install
These functions might be useful for other modules as well.

## Solution
Move these function to the Social Core module.

## Issue tracker
https://www.drupal.org/project/social/issues/3284938
https://getopensocial.atlassian.net/browse/YANG-7827

## How to test
- [ ] Enable social_album module.
- [ ] Create a group. Bundle does not matter.
- [ ] Make sure that **hero** and **statistics** blocks are displayed on the /user/*/albums and /group/*/albums.

## Definition of done
### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] If applicable (I.E. new hook_updates) the update path from previous versions (major and minor versions) are tested
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
Code refactoring.

2022-06-10 07:49 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2985-zedwlkrfkkpgw3guirp8o3yzl8k7k9zf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62a2451dc1600d72c52befbc

2022-06-14 08:28 UTC, Ressinel commented
Hi, @ksis 

Thanks for this code refactoring.
Since functions were renamed we have to create Change records to inform devs about that.

2022-06-14 13:39 UTC, ksis commented
Hi @Ressinel,
I added information about the changes to the PR description.

2022-06-17 10:26 UTC, ribel commented
Hi @ksis,
I think we need to create Change Record on drupal.org. You can see some examples here: https://www.drupal.org/list-changes/social

Also in the description you said:

The _social_album_blocks function was renamed to _social_album_blocks... is that correct?

2022-06-20 10:44 UTC, OH17L requested changes
In general, changes look good to me but still need to make a few following things:

1. See two comments to code.
2. Release notes should be more detailed. For example, you can re-use the title of a pull request.
3. Move text from the change record section to drupal.org and add a link to drupal.org change record to this section.

2022-06-20 10:44 UTC, OH17L commented on modules/social_features/social_core/social_core.module
> + *   The function which updates the pages set.
```suggestion
 *   (optional) The function which updates the pages set. Defaults to NULL.
```

2022-06-20 10:44 UTC, OH17L commented on modules/social_features/social_album/social_album.install
> +  _social_album_blocks(NULL, function ($pages, array $paths) {
I'd say that the function from 2nd argument should be moved to the core module because it might be re-used.

2022-06-20 11:50 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2985-zedwlkrfkkpgw3guirp8o3yzl8k7k9zf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62a2451dc1600d72c52befbc

2022-06-22 07:17 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2985-zedwlkrfkkpgw3guirp8o3yzl8k7k9zf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62a2451dc1600d72c52befbc

2022-06-22 09:08 UTC, OH17L approved these changes

2022-06-22 09:11 UTC, Ressinel commented
@ksis Is the Change Record still in the draft?

2022-06-22 09:24 UTC, ribel reviewed
Changes looks good to me, but I just have a question about Backward Compatibility. 
Not sure if we should still keep old functions: `_social_album_install_blocks()` and `_social_album_install_blocks()`, in case if some other developers still use them by any chance, but mark them as deprecated. 
On other hand those are very specific functions, and chances are low.

But what do you think about it @Ressinel, @tbsiqueira?

2022-06-22 13:14 UTC, Ressinel commented
> Changes looks good to me, but I just have a question about Backward Compatibility. Not sure if we should still keep old functions: `_social_album_install_blocks()` and `_social_album_install_blocks()`, in case if some other developers still use them by any chance, but mark them as deprecated. On other hand those are very specific functions, and chances are low.
> 
> But what do you think about it @Ressinel, @tbsiqueira?

@ribel In my opinion we have to keep those functions and mark them as deprecated and in what version they will be removed. We can't be 100% sure that no one uses them.

2022-06-30 19:42 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2985-zedwlkrfkkpgw3guirp8o3yzl8k7k9zf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62a2451dc1600d72c52befbc

2022-07-01 06:32 UTC, ribel commented on modules/social_features/social_album/social_album.install
> + *
@ksis Please add `@see https://github.com/drupal-graphql/graphql/pull/2985` to fix PHPCS check.

2022-07-01 06:59 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2985-zedwlkrfkkpgw3guirp8o3yzl8k7k9zf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62a2451dc1600d72c52befbc

2022-07-01 09:21 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2985-zedwlkrfkkpgw3guirp8o3yzl8k7k9zf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62a2451dc1600d72c52befbc

2022-07-02 08:35 UTC, Ressinel commented
@ksis I have changed the status to `needs work`. Change it to `needs review` if this PR is already ready to review. Thanks!

2022-07-02 12:55 UTC, ribel commented
@Ressinel I see that @ksis did commit changes that was proposed, so it's actually ready for final review ;)

2022-07-02 13:18 UTC, Ressinel approved these changes

2022-07-04 08:40 UTC, merged

2022-07-04 08:41 UTC, ribel commented
🍒 picked to 11.4.x