Issue #3260291 by sayco: Assertion error on group membership page
goalgorilla/open_social pull request #3041
Opened 2022-07-18 18:29 UTC by Ressinel

## Problem
The group membership page shows an assertion error if the Group Invitation plugin is not installed:
`AssertionError: assert(\Drupal::service('cache_contexts_manager')->assertValidTokens($cache_contexts)) in assert() (line 31 of core/lib/Drupal/Core/Cache/Cache.php).`

## Solution
The old caching tags were used in the action links. Update group and group.role to the route.group cache tag, which should be valid for any routes using the group parameter. Add also the group permission related context, as the link may also depend on that. BTW the group change record of the cache contexts: https://www.drupal.org/node/3011700

## Issue tracker
- https://www.drupal.org/project/social/issues/3260291

## Theme issue tracker
N/A

## How to test
- [ ] Create a new group type (don't install the group invitation plugin)
- [ ] Create a group of that type
- [ ] Visit the membership page
- [ ] ...

## Definition of done
### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
TBD

## Change Record
N/A

## Translations
N/A

2022-07-18 18:34 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3041-mjk7ynwnzp0cvr5ehpohvia6txqe9isa.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62d5a67874ab60d4e818d79d

2022-07-19 06:50 UTC, navneet0693 requested changes
Behat is failing. Please run the failing tests on local.

2022-07-19 07:57 UTC, Ressinel commented
@navneet0693 All tests are passed.

2022-07-19 08:16 UTC, navneet0693 approved these changes

2022-07-19 08:19 UTC, merged