Allow anonymous user access on update hook for flexible groups
goalgorilla/open_social pull request #3104
Opened 2022-09-08 14:58 UTC by NickDaelemans

## Problem
When viewing a public group, anonymous users don't see the album link, although the module is enabled.

## Solution
By adding the right permissions to the anonymous users for flexible groups, anonymous users are able to see both the Albums link and Albums page.

## Issue tracker
*[Required] Paste a link to the drupal.org issue queue item. If any other issue trackers were used, include links to those too.*

## Theme issue tracker
*[Required if applicable] Paste a link to the drupal.org theme issue queue item, either from [socialbase](https://www.drupal.org/project/socialbase) or [socialblue](https://www.drupal.org/project/socialblue). If any other issue trackers were used, include links to those too.*

## How to test
- [ ] Make sure the `social_album` module is installed
- [ ] Create a public group
- [ ] As an anonymous user
- [ ] Open the public group
- [ ] You should see the Albums link
- [ ] Click on the Albums link
- [ ] You should see `No albums in this group`
- [ ] If you add a public album, this should also be visible when viewing the Albums page.

## Definition of done
### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
*[Required if new feature, and if applicable] If this Pull Request makes visual changes then please include some screenshots that show what has changed here. A before and after screenshot helps the reviewer determine what changes were made.*

## Release notes
*[Required if new feature, and if applicable] A short summary of the changes that were made that can be included in release notes.*

## Change Record
*[Required if applicable] If this Pull Request changes the way that developers should do things or introduces a new API for developers then a change record to document this is needed. Please provide a draft for a change record or a link to an unpublished change record below. Existing change records can be consulted as example. Please provide a draft for a change record or a link to an unpublished change record below. [Existing change records](https://www.drupal.org/list-changes/social) can be consulted as example.*

## Translations
*[Optional]Translatable strings are always extracted from the latest development branch. To ensure translations remain available for platforms running older versions of Open Social the original string should be added to `translations.php` when it's changed or removed.*
- [ ] Changed or removed source strings are added to the `translations.php` file.

2022-09-12 06:42 UTC, NickDaelemans commented on modules/social_features/social_album/social_album.install
> +  $group_role_anonymous->grantPermissions(['view group_node:album content', 'view group_node:album entity'])->save();
I do think this needs some proper testing before merging. To answer your questions:

- The group permissions for anonymous users are indeed not available in UI. Hence the `permissions_ui: false` in the `group.role.flexible_group-anonymous.yml` file.
- I think you might be right; what this update should do, is only show the `Album overview` page. However, the view that builds that page uses the `view group_node:album content`, that's why I added it here.
- I think we should indeed add (or replace with) `View node.album.field_content_visibility:public content`. This is the one I enabled on the client to fix the issue that they could not see a single public Album. 

I will work further on this, to investigate the good remarks you made here, thanks!

2022-09-12 13:48 UTC, tbsiqueira commented
Hi @NickDaelemans , thank you for your contribution! 

Can you please create a ticket on d.org for this PR? Also, please add release notes and screenshots of the expected behavieur.

2022-09-12 14:05 UTC, tbsiqueira approved these changes

2022-09-12 14:10 UTC, tbsiqueira requested changes
If there aren't, please add behat tests to cover this change.

- Create album as community content;
- Create algum as group content;
- Create album as public content;
- Create groups with the respective permissions;
- Check if LU and AN users have the right permissions

2022-09-20 08:10 UTC, navneet0693 requested changes

2022-09-20 08:10 UTC, navneet0693 commented on modules/social_features/social_album/social_album.install
> +      'view node.album.field_content_visibility:community content',
I see that this was already added in https://github.com/goalgorilla/open_social/blob/main/modules/social_features/social_album/social_album.install#L28, did few a reason why it was missed being added ?

2022-09-20 08:10 UTC, navneet0693 commented on modules/social_features/social_album/social_album.install
> +  /** @var \Drupal\group\Entity\GroupRoleInterface $group_role_outsider */
I think we can remove it, if we call `_social_album_set_group_permissions` and changes are added to that function.

2022-09-22 11:26 UTC, NickDaelemans commented
Since we are not doing the Behat tests here, I created a new PR here: https://github.com/goalgorilla/open_social/pull/3121

2022-09-22 11:26 UTC, closed without merging