Issue #3313504 by vnech: Make "basic_html" text format default for posts
goalgorilla/open_social pull request #3144
Opened 2022-10-04 17:49 UTC by nechai

## Problem
The post field field_post with the text doesn't allows to user to choose text format. After submitting this field gets the most higher text format in the list from *admin/config/content/formats*. 

That means that the posts can have text with different text format and, as a result, different text displaying. 

This also create an issue with mentions if I add some custom text format with the highest weight like this:
<img width="1583" alt="Screenshot 2022-10-04 at 20 29 11" src="https://user-images.githubusercontent.com/19921926/193889074-3e72f326-018a-4550-af0b-b206c54340c3.png">

Mentions in post:
<img width="646" alt="Screenshot 2022-10-04 at 20 44 24" src="https://user-images.githubusercontent.com/19921926/193889484-3930de4f-d232-46ce-abc0-1ef9ed34c3c4.png">

## Solution
- Make `basic_html` as a default text format for posts

## Issue tracker
- https://www.drupal.org/project/social/issues/3313504
- https://getopensocial.atlassian.net/browse/PROD-22258

## Theme issue tracker
n/a

## How to test
- [ ] Login as an admin
- [ ] Add a new text format and make it the highest weight on *admin/config/content/formats*
- [ ] Create a post with mentions

## Definition of done
### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
n/a

## Release notes
*Make `basic_html` as a default text format for posts.*

## Change Record
n/a

## Translations
n/a

2022-10-05 18:37 UTC, nechai commented
Hi @ribel! Seems like we have this issue with any of `text` and `text_long` field types. 

I [suggest](https://github.com/goalgorilla/open_social/pull/3144/commits/7a68dcddfb7c4a3bd649ffa1dba4e06527a63c6e) to specify `basic_html` text format for these field types if explicitly the text format was not chosen by users from ui.

2022-10-06 06:07 UTC, ribel commented
@nechai I am not sure if we need to hardcode it for ALL `text` and `text_long` field types, because other Open Social might have their own text formats for reason.
So I think it's actually better to limit it only for our Comments and Posts.

2022-10-22 04:27 UTC, navneet0693 commented
@nechai Please resolve the failing tests.

2022-11-01 15:16 UTC, ribel requested changes
Hi @nechai,
I still think it's bad idea to hardcode `basic_html` for all fields of `text` and `text_long` types.
Please take a look to function `social_core_filter_process_format()`, where we have more complex logic, which covers specific body fields, and also take into account `full_html` format and permissions to use specific format.

2022-11-10 09:44 UTC, ribel commented
I think this PR can be closed, since we fixed issue in related extension: https://github.com/goalgorilla/cablecar/pull/120

2022-11-10 09:44 UTC, closed without merging