Issue #3314447 by rolki: Fix flexible group visibility checking
goalgorilla/open_social pull request #3150
Opened 2022-10-10 10:14 UTC by rollki

## Problem
*[Required] Describe the problem you're trying to solve, this should motivate why the changes you're proposing are needed.*

## Solution
*[Required] Describe the solution you've created, elaborate on any technical choices you've made. Why is this the right solution and is a different solution not the right one? What is the reasoning behind the chosen solution?*

## Issue tracker
*[Required] Paste a link to the drupal.org issue queue item. If any other issue trackers were used, include links to those too.*

## Theme issue tracker
*[Required if applicable] Paste a link to the drupal.org theme issue queue item, either from [socialbase](https://www.drupal.org/project/socialbase) or [socialblue](https://www.drupal.org/project/socialblue). If any other issue trackers were used, include links to those too.*

## How to test
*[Required] For example*
- [ ] Using version X.Y.Z of Open Social with the example module enabled
- [ ] As a sitemanager
- [ ] Try to enable the option B on screen c/d/e
- [ ] When saving I expect the result to be F but instead see G.
- [ ] The expected result F is attained when repeating the steps with this fix applied.

## Definition of done
### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
*[Required if new feature, and if applicable] If this Pull Request makes visual changes then please include some screenshots that show what has changed here. A before and after screenshot helps the reviewer determine what changes were made.*

## Release notes
*[Required if new feature, and if applicable] A short summary of the changes that were made that can be included in release notes.*

## Change Record
*[Required if applicable] If this Pull Request changes the way that developers should do things or introduces a new API for developers then a change record to document this is needed. Please provide a draft for a change record or a link to an unpublished change record below. Existing change records can be consulted as example. Please provide a draft for a change record or a link to an unpublished change record below. [Existing change records](https://www.drupal.org/list-changes/social) can be consulted as example.*

## Translations
*[Optional]Translatable strings are always extracted from the latest development branch. To ensure translations remain available for platforms running older versions of Open Social the original string should be added to `translations.php` when it's changed or removed.*
- [ ] Changed or removed source strings are added to the `translations.php` file.

2022-11-02 12:56 UTC, ribel requested changes
Hi @rollki,
I see there are failing behat tests related to Flexible group, so we need to check them.

2022-11-22 12:11 UTC, rollki commented
Hi guys, this PR was created due to an issue on Sparkblue (https://getopensocial.atlassian.net/browse/PROD-22582), I'm not sure about the changes made in this PR, but from the names of the methods they seem logical to me, check by group visibility, not group content visibility.
These changes were also added to the production of one of the projects, and it seems that they work normally there, so I would like to hear your opinion, maybe the check by group content visibility was written deliberately, but then why is it not aligned with the name of the methods.

cc @ronaldtebrake, @tbsiqueira, @ribel

2023-01-27 12:56 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3150-mvuphpkjmdrnxqqhd7eurxr8qby71izq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63d3c9d3127cbc4c566cdf29

2023-01-28 00:24 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3150-mvuphpkjmdrnxqqhd7eurxr8qby71izq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63d3c9d3127cbc4c566cdf29

2023-01-29 00:25 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3150-mvuphpkjmdrnxqqhd7eurxr8qby71izq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63d3c9d3127cbc4c566cdf29

2023-01-30 00:24 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3150-mvuphpkjmdrnxqqhd7eurxr8qby71izq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63d3c9d3127cbc4c566cdf29

2023-01-31 00:22 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3150-mvuphpkjmdrnxqqhd7eurxr8qby71izq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63d3c9d3127cbc4c566cdf29

2023-01-31 10:08 UTC, ribel approved these changes
I have tested changes and it looks good and logical to me.
Changes from Roman seems to be correct and logical. Not sure if it may have negative impact on existing Groups and it's visibility, but it's something to keep in mind and maybe mention in release notes.

2023-01-31 10:10 UTC, nechai approved these changes

2023-02-01 00:24 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3150-mvuphpkjmdrnxqqhd7eurxr8qby71izq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63d3c9d3127cbc4c566cdf29

2023-02-02 00:22 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3150-mvuphpkjmdrnxqqhd7eurxr8qby71izq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63d3c9d3127cbc4c566cdf29

2023-02-03 00:21 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3150-mvuphpkjmdrnxqqhd7eurxr8qby71izq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63d3c9d3127cbc4c566cdf29

2023-02-04 00:21 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3150-mvuphpkjmdrnxqqhd7eurxr8qby71izq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63d3c9d3127cbc4c566cdf29

2023-02-05 00:21 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3150-mvuphpkjmdrnxqqhd7eurxr8qby71izq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63d3c9d3127cbc4c566cdf29

2023-02-06 00:21 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3150-mvuphpkjmdrnxqqhd7eurxr8qby71izq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63d3c9d3127cbc4c566cdf29

2023-02-07 00:21 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3150-mvuphpkjmdrnxqqhd7eurxr8qby71izq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63d3c9d3127cbc4c566cdf29

2023-02-08 00:21 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3150-mvuphpkjmdrnxqqhd7eurxr8qby71izq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63d3c9d3127cbc4c566cdf29

2023-02-09 00:23 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3150-mvuphpkjmdrnxqqhd7eurxr8qby71izq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63d3c9d3127cbc4c566cdf29

2023-02-10 00:22 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3150-mvuphpkjmdrnxqqhd7eurxr8qby71izq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63d3c9d3127cbc4c566cdf29

2023-02-11 00:19 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3150-mvuphpkjmdrnxqqhd7eurxr8qby71izq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63d3c9d3127cbc4c566cdf29

2023-02-12 00:28 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3150-mvuphpkjmdrnxqqhd7eurxr8qby71izq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63d3c9d3127cbc4c566cdf29

2023-02-13 00:18 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3150-mvuphpkjmdrnxqqhd7eurxr8qby71izq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63d3c9d3127cbc4c566cdf29

2023-02-13 10:19 UTC, BiaInacio commented
Hi all,
I have found the following issue, could you please check?

**Summary:** Stream content is not displayed even though the users can see that some content that was created on other tabs
**Pre-contition:** to have access the site, to have a public content, like a topic, created on a public flexible group
**Steps:**
1. Access the site as any user, logged or not, that is not member of the public group.
2. Open the stream of a public flexible group that has public content created (like a topic)

Expected result: Stream of the group should show the creation of the content that the user viewing has access to view
Actual result: nothing, not even a warning message of no content is displayed on the stream page

**Evidences**
Page URL: https://pr3150-mvuphpkjmdrnxqqhd7eurxr8qby71izq.tugboatqa.com/group/6/stream
test it with the user michelleclark / michelleclark
![image](https://user-images.githubusercontent.com/9381456/218431539-05198fb7-432d-46e0-a209-cfb045d83076.png)
![image](https://user-images.githubusercontent.com/9381456/218431572-cddc4fbd-522d-4f29-9c16-73baac5242ae.png)

2023-02-13 12:17 UTC, tbsiqueira approved these changes

2023-02-13 12:23 UTC, merged

2023-02-13 12:27 UTC, ribel commented
🍒 -picked to 11.6.x and 11.7.x