Issue #3324960 by nkoporec: Make user greeting optional for certain emails
goalgorilla/open_social pull request #3234
Opened 2022-12-02 12:02 UTC by nkoporec

## Problem
Currently we hardcode the user greeting when we sent any email, eq: (https://monosnap.com/file/B5sMPud3I3kTSHdFO7il7AcnVW7ca7)

This is not ideal and it would be good to have some kind of setting where you could configure this.

## Solution
Add a setting to social_swiftmailer, where you can define on which message keys this will be turned off.

## Issue tracker
https://www.drupal.org/project/social/issues/3324960

## Theme issue tracker
*[Required if applicable] Paste a link to the drupal.org theme issue queue item, either from [socialbase](https://www.drupal.org/project/socialbase) or [socialblue](https://www.drupal.org/project/socialblue). If any other issue trackers were used, include links to those too.*

## How to test
1. Install Open Social
2. Create a new account
3. Check that you have two greetings in the email.

## Definition of done
### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
<img width="592" alt="MailHog+2022-12-02+12-39-44" src="https://user-images.githubusercontent.com/35064680/205288406-03bea2f2-efb9-46e7-bc15-fc9aa676e3a2.png">

## Release notes
Added a setting to social_swiftmailer module to optionally opt-out of user greeting in an email.

## Change Record
*[Required if applicable] If this Pull Request changes the way that developers should do things or introduces a new API for developers then a change record to document this is needed. Please provide a draft for a change record or a link to an unpublished change record below. Existing change records can be consulted as example. Please provide a draft for a change record or a link to an unpublished change record below. [Existing change records](https://www.drupal.org/list-changes/social) can be consulted as example.*

## Translations
*[Optional]Translatable strings are always extracted from the latest development branch. To ensure translations remain available for platforms running older versions of Open Social the original string should be added to `translations.php` when it's changed or removed.*
- [ ] Changed or removed source strings are added to the `translations.php` file.

2022-12-06 09:20 UTC, navneet0693 requested changes

2022-12-06 09:20 UTC, navneet0693 commented on modules/social_features/social_swiftmail/social_swiftmail.install
> +function social_swiftmail_update_9000(): void {
Please change the update hook number to `11001`.

We should not have hook_update_N, where N is 8000, or 9000, as referenced in https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Extension%21module.api.php/function/hook_update_N/8.2.x

```
Note that the x000 number can never be used: the lowest update number that will be recognized and run for major version x is x001.
```

2022-12-06 09:22 UTC, navneet0693 commented
@nkoporec Please update the release notes to be more "user friendly" which can be sent to clients/customer directly. 
HTT doesn't seems to reflect the changes we need to tests.
Also, please elaborate the solution more with more examples and screenshots.

2022-12-06 14:13 UTC, nkoporec commented
@navneet0693 I updated the code and all other issues that you have found (eq, HTT, release notes), please let me know if it looks better now.

I agree that solutions is quite technical, but on the other side, its always nice to have this as a configurable config rather then having it hard-coded.  I presume that this setting will be set as default value almost all the time and only be overridden in certain sites.

2022-12-16 00:04 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3234-olyptvq6mtt5crryoxfntipim5ctm2o4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6389e96032d30df7acb6705e

2022-12-17 00:04 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3234-olyptvq6mtt5crryoxfntipim5ctm2o4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6389e96032d30df7acb6705e

2022-12-18 00:04 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3234-olyptvq6mtt5crryoxfntipim5ctm2o4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6389e96032d30df7acb6705e

2022-12-19 00:04 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3234-olyptvq6mtt5crryoxfntipim5ctm2o4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6389e96032d30df7acb6705e

2022-12-20 00:04 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3234-olyptvq6mtt5crryoxfntipim5ctm2o4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6389e96032d30df7acb6705e

2022-12-21 00:04 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3234-olyptvq6mtt5crryoxfntipim5ctm2o4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6389e96032d30df7acb6705e

2022-12-22 00:04 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3234-olyptvq6mtt5crryoxfntipim5ctm2o4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6389e96032d30df7acb6705e

2022-12-23 00:04 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3234-olyptvq6mtt5crryoxfntipim5ctm2o4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6389e96032d30df7acb6705e

2022-12-24 00:04 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3234-olyptvq6mtt5crryoxfntipim5ctm2o4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6389e96032d30df7acb6705e

2022-12-25 00:04 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3234-olyptvq6mtt5crryoxfntipim5ctm2o4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6389e96032d30df7acb6705e

2022-12-26 00:04 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3234-olyptvq6mtt5crryoxfntipim5ctm2o4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6389e96032d30df7acb6705e

2022-12-27 00:04 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3234-olyptvq6mtt5crryoxfntipim5ctm2o4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6389e96032d30df7acb6705e

2022-12-28 00:04 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3234-olyptvq6mtt5crryoxfntipim5ctm2o4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6389e96032d30df7acb6705e

2022-12-30 00:04 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3234-olyptvq6mtt5crryoxfntipim5ctm2o4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6389e96032d30df7acb6705e

2022-12-31 00:04 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3234-olyptvq6mtt5crryoxfntipim5ctm2o4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6389e96032d30df7acb6705e

2023-01-01 00:04 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3234-olyptvq6mtt5crryoxfntipim5ctm2o4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6389e96032d30df7acb6705e

2023-01-02 00:04 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3234-olyptvq6mtt5crryoxfntipim5ctm2o4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6389e96032d30df7acb6705e

2023-01-03 00:04 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3234-olyptvq6mtt5crryoxfntipim5ctm2o4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6389e96032d30df7acb6705e

2023-01-04 00:04 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3234-olyptvq6mtt5crryoxfntipim5ctm2o4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6389e96032d30df7acb6705e

2023-01-06 11:56 UTC, nkoporec commented
@tbsiqueira any input here ?

2023-01-07 00:04 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3234-olyptvq6mtt5crryoxfntipim5ctm2o4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6389e96032d30df7acb6705e

2023-01-10 00:04 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3234-olyptvq6mtt5crryoxfntipim5ctm2o4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6389e96032d30df7acb6705e

2023-01-11 00:04 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3234-olyptvq6mtt5crryoxfntipim5ctm2o4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6389e96032d30df7acb6705e

2023-01-11 09:59 UTC, tbsiqueira commented
Hi @nkoporec 

Thank you for your work. 

I'm missing more screenshots of the screen that has the new option, and tests.

2023-01-12 00:04 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3234-olyptvq6mtt5crryoxfntipim5ctm2o4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6389e96032d30df7acb6705e

2023-01-14 00:04 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3234-olyptvq6mtt5crryoxfntipim5ctm2o4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6389e96032d30df7acb6705e

2023-01-15 00:05 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3234-olyptvq6mtt5crryoxfntipim5ctm2o4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6389e96032d30df7acb6705e

2023-01-16 00:04 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3234-olyptvq6mtt5crryoxfntipim5ctm2o4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6389e96032d30df7acb6705e

2023-01-17 00:04 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3234-olyptvq6mtt5crryoxfntipim5ctm2o4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6389e96032d30df7acb6705e

2023-01-18 00:05 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3234-olyptvq6mtt5crryoxfntipim5ctm2o4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6389e96032d30df7acb6705e

2023-01-19 08:59 UTC, merged

2023-01-19 09:03 UTC, tbsiqueira commented
Cherry-picked to 11.7.x