Issue #3370849 by nkoporec: Can't add an image to the existing album on stream page
goalgorilla/open_social pull request #3442
Opened 2023-06-28 06:37 UTC by nkoporec

## Problem
When using social_album and I want to add an image to stream using the default /stream page, I see that a field widget is displayed to also add this image to an album, but the options there are always "None" or "Create a new album", even if I already have multiple albums created. So it should be possible to select an existing album.

I have multiple public albums created:
![2023-06-28_08-28](https://github.com/goalgorilla/open_social/assets/35064680/6cd725e8-13d0-4a03-b735-bb732146fad7)

I don't see them in the field widget:

![2023-06-28_08-27](https://github.com/goalgorilla/open_social/assets/35064680/79dc52c9-1f49-45c2-9df1-36bfc665df7f)

## Solution
We need to update the custom field widget to allow selecting an existing albums.

## Issue tracker
https://www.drupal.org/project/social/issues/3370849

## Theme issue tracker
*[Required if applicable] Paste a link to the drupal.org theme issue queue item, either from [socialbase](https://www.drupal.org/project/socialbase) or [socialblue](https://www.drupal.org/project/socialblue). If any other issue trackers were used, include links to those too.*

## How to test
1. Install social_album
2. Create a new public album
3. Go to /stream page and click on 'Add images'
4. Add an image, you should see the `Add image(s) to an album` field widget
5. Try to select an album that you created in step 2.

## Definition of done
### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots

Before:
![2023-06-28_08-27](https://github.com/goalgorilla/open_social/assets/35064680/db2e2278-93e4-44de-9d04-e892306d34a5)

After:

![image](https://github.com/goalgorilla/open_social/assets/35064680/56cd4cd3-7b2a-4725-b40f-2a25be26c628)

## Release notes
Added the ability to add images directly to existing albums via the stream page.

## Change Record

## Translations

2023-06-28 06:37 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3442-n1o2bgtglsebhagxwlbk8ympvrmkfnkc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649bd517757563ca371eccda

2023-06-29 00:35 UTC, Kingdutch commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3442-n1o2bgtglsebhagxwlbk8ympvrmkfnkc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649bd517757563ca371eccda

2023-06-29 05:47 UTC, Kingdutch commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3442-n1o2bgtglsebhagxwlbk8ympvrmkfnkc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649bd517757563ca371eccda

2023-06-29 08:39 UTC, zanvidmar commented on tests/behat/features/bootstrap/AlbumContext.php
> +  public function whenICreateABookUsingTheForm(TableNode $fields): void {
Change whenICreateA**Book**UsingTheForm to whenICreate**AnAlbum**UsingTheForm

2023-06-29 08:39 UTC, zanvidmar commented on tests/behat/features/bootstrap/AlbumContext.php
> +   * Example: When I create a album using its creation page:
Typo `a album` => `an album`

2023-06-29 08:41 UTC, zanvidmar commented on tests/behat/features/capabilities/post/post-album-existing.feature
> +    When I create a album using its creation page:
Typo `a album` => `an album`

2023-06-29 09:11 UTC, zanvidmar commented on tests/behat/features/bootstrap/AlbumContext.php
> +use Drupal\Component\Plugin\Exception\PluginNotFoundException;
PluginNotFoundException is not used. Please remove it.

2023-06-29 09:12 UTC, zanvidmar commented on tests/behat/features/bootstrap/AlbumContext.php
> +use Drupal\node\Entity\Node;
Drupal\group\Entity\Group and Drupal\node\Entity\Node are not used. Please remove them.

2023-06-29 09:25 UTC, zanvidmar commented on tests/behat/features/bootstrap/AlbumContext.php
> +      elseif ($key === "description") {
There is no "description" in Album.

2023-06-29 09:33 UTC, zanvidmar requested changes
Please check my comments in code. Thank you 🙂

2023-06-30 00:35 UTC, Kingdutch commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3442-n1o2bgtglsebhagxwlbk8ympvrmkfnkc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649bd517757563ca371eccda

2023-06-30 06:10 UTC, Kingdutch commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3442-n1o2bgtglsebhagxwlbk8ympvrmkfnkc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649bd517757563ca371eccda

2023-06-30 08:07 UTC, zanvidmar commented on tests/behat/features/bootstrap/AlbumContext.php
> +  private CKEditorContext $cKEditorContext;
Do you still want to keep CKEditorContext, while this is not used at the moment?

2023-06-30 08:08 UTC, zanvidmar commented on tests/behat/features/bootstrap/AlbumContext.php
> +    $this->cKEditorContext = $environment->getContext(CKEditorContext::class);
Do you still want to keep CKEditorContext, while this is not used at the moment?

2023-06-30 08:09 UTC, zanvidmar commented on tests/behat/features/bootstrap/AlbumContext.php
> +        // Changing the group of a album updates the visibility settings so we
Typo: a album => an album

2023-06-30 08:09 UTC, zanvidmar commented on tests/behat/features/bootstrap/AlbumContext.php
> +      // Changing the group of a album updates the visibility settings so we must
Typo: a album => an album

2023-06-30 08:13 UTC, zanvidmar commented on tests/behat/features/bootstrap/AlbumContext.php
> +use Drupal\DrupalExtension\Context\DrupalContext;
Do you still want to keep DrupalContext, while this is not used at the moment?

2023-06-30 08:13 UTC, zanvidmar commented on tests/behat/features/bootstrap/AlbumContext.php
> +    $this->drupalContext = $environment->getContext(SocialDrupalContext::class);
Do you still want to keep DrupalContext, while this is not used at the moment?

2023-06-30 08:13 UTC, zanvidmar commented on tests/behat/features/bootstrap/AlbumContext.php
> +  private DrupalContext $drupalContext;
Do you still want to keep DrupalContext, while this is not used at the moment?

2023-06-30 13:47 UTC, Kingdutch commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3442-n1o2bgtglsebhagxwlbk8ympvrmkfnkc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649bd517757563ca371eccda

2023-07-01 00:35 UTC, Kingdutch commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3442-n1o2bgtglsebhagxwlbk8ympvrmkfnkc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649bd517757563ca371eccda

2023-07-02 00:35 UTC, Kingdutch commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3442-n1o2bgtglsebhagxwlbk8ympvrmkfnkc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649bd517757563ca371eccda

2023-07-03 00:36 UTC, Kingdutch commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3442-n1o2bgtglsebhagxwlbk8ympvrmkfnkc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649bd517757563ca371eccda

2023-07-03 20:28 UTC, BiaInacio commented
Change is working as expected!
<img width="838" alt="image" src="https://github.com/goalgorilla/open_social/assets/9381456/0a2113b4-9804-46b9-a20d-2a0ee78c3209">

2023-07-04 00:37 UTC, Kingdutch commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3442-n1o2bgtglsebhagxwlbk8ympvrmkfnkc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649bd517757563ca371eccda

2023-07-05 00:33 UTC, Kingdutch commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3442-n1o2bgtglsebhagxwlbk8ympvrmkfnkc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649bd517757563ca371eccda

2023-07-05 07:06 UTC, zanvidmar approved these changes

2023-07-05 14:21 UTC, Kingdutch commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3442-n1o2bgtglsebhagxwlbk8ympvrmkfnkc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649bd517757563ca371eccda

2023-07-05 14:23 UTC, Kingdutch commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3442-n1o2bgtglsebhagxwlbk8ympvrmkfnkc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649bd517757563ca371eccda

2023-07-05 16:14 UTC, merged

2023-07-05 16:33 UTC, zanvidmar commented
🍒 cherry picked

Cherry-picked to 11.8.x here: [0c2e368fc](https://github.com/goalgorilla/open_social/commit/0c2e368fc4ed033a53695c774c236164e3158886)
Cherry-picked to 11.9.x here: [655c43dca](https://github.com/goalgorilla/open_social/commit/655c43dcab7674c8fa874bef8412273e8f769c40)