PROD-26095: Change preview for comment and post to fix mentions in em…
goalgorilla/open_social pull request #3475
Opened 2023-08-08 14:06 UTC by Kovalskiy266

## Problem
When we mention other users in comments or in posts, an email is sent to them to notify them. But we have a problem -  instead of the names of the users mentioned, we see their IDs in the email. This is not correct. This problem has been here for quite some time, previously it was discussed here - https://github.com/goalgorilla/open_social/pull/1873

## Solution
Change the code for comment and post previews by applying a mention filter with settings. This way, the [message:preview] token will display the correct result

## Issue tracker
https://www.drupal.org/project/social/issues/3069371

## Theme issue tracker
N/A

## How to test
- [ ] Create comment reply or post
- [ ] You need to make sure you also mention the person in the comment or in the post on the profile with the @mention function. (better create two users, the first user will write a comment and mention the second user, the letter should come to the second user)
- [ ] Run cron manually or wait for the cron to start automatically
- [ ] Go to emails, and look at the letter
- [ ] The expected result is that we should see the names of users, not numbers (their ids)
-->

## Definition of done
### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
It should not look like this:
<img width="1460" alt="Screenshot 2023-08-08 at 17 00 56" src="https://github.com/goalgorilla/open_social/assets/85495223/0ee7aac8-31f4-4132-85c4-c13c230de862">
It should be like this:
<img width="1461" alt="Screenshot 2023-08-08 at 17 00 39" src="https://github.com/goalgorilla/open_social/assets/85495223/091614ed-7f1d-4940-8782-9da2b63b52f7">

## Release notes
We have solved a problem where email notifications containing mentions would not get converted to the correct display name but instead showed an id.

## Change Record
N/A

## Translations
N/A

2023-08-08 14:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3475-vwmmjyfemz8bubygt6dlzb9gudehciqt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64d24bfbf70224ca09c86e57

2023-08-08 15:05 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3475-vwmmjyfemz8bubygt6dlzb9gudehciqt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64d24bfbf70224ca09c86e57

2023-08-09 00:50 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3475-vwmmjyfemz8bubygt6dlzb9gudehciqt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64d24bfbf70224ca09c86e57

2023-08-09 07:22 UTC, ribel requested changes
Hi @Kovalskiy266,
I see there is failing tests related to mention, so we need to check and fix them.

2023-08-09 14:27 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3475-vwmmjyfemz8bubygt6dlzb9gudehciqt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64d24bfbf70224ca09c86e57

2023-08-09 15:22 UTC, Kovalskiy266 commented
@ribel Hello
Done

> Hi @Kovalskiy266, I see there is failing tests related to mention, so we need to check and fix them.

@ribel Hello
Done

2023-08-10 00:48 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3475-vwmmjyfemz8bubygt6dlzb9gudehciqt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64d24bfbf70224ca09c86e57

2023-08-11 00:49 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3475-vwmmjyfemz8bubygt6dlzb9gudehciqt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64d24bfbf70224ca09c86e57

2023-08-12 00:49 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3475-vwmmjyfemz8bubygt6dlzb9gudehciqt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64d24bfbf70224ca09c86e57

2023-08-13 00:48 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3475-vwmmjyfemz8bubygt6dlzb9gudehciqt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64d24bfbf70224ca09c86e57

2023-08-14 00:50 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3475-vwmmjyfemz8bubygt6dlzb9gudehciqt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64d24bfbf70224ca09c86e57

2023-08-15 00:49 UTC, Kingdutch commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3475-vwmmjyfemz8bubygt6dlzb9gudehciqt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64d24bfbf70224ca09c86e57

2023-08-15 12:28 UTC, ribel approved these changes
Changes were tested and worked as expected now.
<img width="698" alt="image" src="https://github.com/goalgorilla/open_social/assets/2241917/e3cd70ea-9612-4c94-bdf4-979a1da4b92f">

2023-08-16 00:50 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3475-vwmmjyfemz8bubygt6dlzb9gudehciqt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64d24bfbf70224ca09c86e57

2023-08-17 00:47 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3475-vwmmjyfemz8bubygt6dlzb9gudehciqt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64d24bfbf70224ca09c86e57

2023-08-18 00:46 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3475-vwmmjyfemz8bubygt6dlzb9gudehciqt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64d24bfbf70224ca09c86e57

2023-08-18 09:15 UTC, tbsiqueira approved these changes

2023-08-18 10:34 UTC, merged

2023-08-18 10:35 UTC, ribel commented
🍒 picked to 11.10.x and 11.9.x