Issue #3382821: Remove deprecated hooks
goalgorilla/open_social pull request #3529
Opened 2023-09-15 11:53 UTC by zanvidmar

Replace deprecated hook_field_widget_form_alter() with hook_field_widget_single_element_form_alter and
hook_field_widget_WIDGET_TYPE_form_alter() with
hook_field_widget_single_element_WIDGET_TYPE_form_alter

## Problem
Change records: https://www.drupal.org/node/3180429

## Solution
Replace deprecated hooks

## Issue tracker
[3387564](https://www.drupal.org/project/social/issues/3387564)

## Theme issue tracker
N/A

## How to test
- [ ] Make sure all tests are green

## Definition of done
### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
Replace deprecated hook_field_widget_form_alter() with hook_field_widget_single_element_form_alter and
hook_field_widget_WIDGET_TYPE_form_alter() with hook_field_widget_single_element_WIDGET_TYPE_form_alter.

## Change Record
N/A

## Translations
N/A

2023-09-15 11:54 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3529-l3we8fsmz19j8p3sdjrd5qjwrrpmlkrp.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/650445c756f783925fff0b8f

2023-09-15 14:56 UTC, nkoporec requested changes
The code changes looks good, but I'm missing more info on how to test it, only relying on tests seems a bit risky. Can you add some HTT steps, for example one HTT would be if a certain widget displays correctly after it has been modified in the hook. That way @BiaInacio can also test this.

Also can you add more info on description ? I can't really understand why this change is necessary solely from the description. 

Is this a breaking change ? Eq. Do we need to update the cablecar extensions as well ? If so, should we update the milestone to 12.0 ?

2023-09-16 01:06 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3529-l3we8fsmz19j8p3sdjrd5qjwrrpmlkrp.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/650445c756f783925fff0b8f

2023-09-17 01:11 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3529-l3we8fsmz19j8p3sdjrd5qjwrrpmlkrp.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/650445c756f783925fff0b8f

2023-09-18 01:39 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3529-l3we8fsmz19j8p3sdjrd5qjwrrpmlkrp.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/650445c756f783925fff0b8f

2023-09-19 01:03 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3529-l3we8fsmz19j8p3sdjrd5qjwrrpmlkrp.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/650445c756f783925fff0b8f

2023-09-20 00:56 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3529-l3we8fsmz19j8p3sdjrd5qjwrrpmlkrp.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/650445c756f783925fff0b8f

2023-09-20 11:26 UTC, zanvidmar commented
@nkoporec Thank you for your comment. I updated HTT in a way that you and @BiaInacio can test this now.

2023-09-21 00:58 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3529-l3we8fsmz19j8p3sdjrd5qjwrrpmlkrp.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/650445c756f783925fff0b8f

2023-09-21 18:37 UTC, BiaInacio commented
HTT 1: works as expected ✅ 
![image](https://github.com/goalgorilla/open_social/assets/9381456/5679e727-3b8c-4669-856a-8fecabf3bc05)

HTT2: works as expected ✅ 
![image](https://github.com/goalgorilla/open_social/assets/9381456/be01e764-9643-4d49-95da-107aeb247a90)

HTT3: works as expected ✅ 
![image](https://github.com/goalgorilla/open_social/assets/9381456/b150f0e4-fb66-40f0-9182-088c43b154e7)

HTT4: works as expected ✅ 
![image](https://github.com/goalgorilla/open_social/assets/9381456/a5f81261-9d74-46fa-8391-e347a5349e94)

HTT5: Sadly I was not able complete the test as the "Use Layout Builder" option on "admin/structure/types/manage/landing_page/display" ❌ 
![image](https://github.com/goalgorilla/open_social/assets/9381456/2a3a7382-4edb-4127-be13-18a311b28795)

HTT6: works as expected ✅ 
![image](https://github.com/goalgorilla/open_social/assets/9381456/bde38095-4fce-4d48-8091-c5087dc2e45d)

HTT7: works as expected ✅ 
![image](https://github.com/goalgorilla/open_social/assets/9381456/9190ebe3-e9e5-4600-baaf-e14f4175cfeb)

HTT8: works as expected ✅ 
![image](https://github.com/goalgorilla/open_social/assets/9381456/1cce7b8e-0957-4ff6-adf6-0514952a6bcb)

HTT9: works as expected ✅ 
![image](https://github.com/goalgorilla/open_social/assets/9381456/2315ccd8-d68a-43a7-af5e-b834402823b6)

HTT10: works as expected ✅ 
![image](https://github.com/goalgorilla/open_social/assets/9381456/f2a2eff5-faaa-41cb-b96f-9027a7d554db)

2023-09-22 12:28 UTC, BiaInacio commented
HTT5: works as expected ✅
![image](https://github.com/goalgorilla/open_social/assets/9381456/eb1e2e72-b0c1-4976-904b-a16030994a06)

All good!!

2023-09-23 00:50 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3529-l3we8fsmz19j8p3sdjrd5qjwrrpmlkrp.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/650445c756f783925fff0b8f

2023-09-24 00:49 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3529-l3we8fsmz19j8p3sdjrd5qjwrrpmlkrp.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/650445c756f783925fff0b8f

2023-09-25 00:51 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3529-l3we8fsmz19j8p3sdjrd5qjwrrpmlkrp.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/650445c756f783925fff0b8f

2023-09-26 00:42 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3529-l3we8fsmz19j8p3sdjrd5qjwrrpmlkrp.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/650445c756f783925fff0b8f

2023-09-27 00:43 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3529-l3we8fsmz19j8p3sdjrd5qjwrrpmlkrp.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/650445c756f783925fff0b8f

2023-09-27 07:33 UTC, merged

2023-09-27 07:45 UTC, zanvidmar commented
🍒  Cherry-picked to 12.0.x here: [53d795fb9](https://github.com/goalgorilla/open_social/commit/53d795fb9c4d5f8f4cba86608fdbc5c64b333be9)