Issue #3402828: Invalidate cache for Featured Event
goalgorilla/open_social pull request #3612
Opened 2023-11-20 12:27 UTC by VBaldych

## Problem
Event with view mode "Featured" still "ongoing" after the event ends.

## Solution
Invalidate cache for the 'Featured' view mode on Events.

## Issue tracker
 - https://getopensocial.atlassian.net/browse/PROD-27131
 - https://www.drupal.org/project/social/issues/3402828

## Theme issue tracker
N/A

## How to test
- [ ] Create an event. The end event time should be a few minutes older than the current date. Save
- [ ] Open an any page with LB
- [ ] Add "Featured" block
- [ ] Choose your created event
- [ ] Save LB
- [ ] Wait the end event time and reload page - you shouldn't see "Ongoing" label

## Definition of done
### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots

## Release notes

## Change Record

## Translations

2023-11-20 12:28 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-11-20 12:39 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-11-20 13:00 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-11-20 13:05 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-11-21 00:21 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-11-21 12:50 UTC, ribel requested changes

2023-11-21 12:50 UTC, ribel commented on modules/social_features/social_event/social_event.module
> +        $variables['#cache']['max-age'] = 0;
Hi @VBaldych,
It's not a good practice to add max-age 0. 
We need to check if we have other ways to solve this issue.
For example check `social_event_node_view_alter()` where we add some cache tags and context to the even teaser.

Also we need to compare featured view mode with normal teaser.
Srtrange if we have issue only in featured.

2023-11-22 00:21 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-11-23 00:21 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-11-24 00:21 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-11-25 00:21 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-11-26 00:22 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-11-27 00:21 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-11-28 00:19 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-11-29 00:19 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-11-30 00:20 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-12-01 00:19 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-12-02 00:19 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-12-03 00:20 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-12-04 00:20 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-12-05 00:21 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-12-06 00:20 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-12-07 00:21 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-12-08 00:18 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-12-09 00:15 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-12-10 00:16 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-12-11 00:18 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-12-13 00:19 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-12-14 00:19 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-12-15 00:18 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-12-16 00:18 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-12-17 00:19 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-12-18 00:19 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-12-19 00:18 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-12-21 00:14 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-12-22 00:13 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-12-23 00:13 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-12-24 00:14 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-12-25 00:14 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-12-26 00:14 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-12-27 00:13 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-12-28 00:13 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-12-29 00:14 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-12-30 00:13 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2023-12-31 00:21 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-01-01 00:17 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-01-02 00:16 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-01-03 00:23 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-01-04 14:20 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-01-05 00:17 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-01-06 00:13 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-01-07 00:12 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-01-08 00:14 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-01-09 00:14 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-01-10 00:14 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-01-11 00:12 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-01-12 00:15 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-01-13 00:16 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-01-15 00:13 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-01-16 00:16 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-01-17 00:11 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-01-18 00:12 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-01-19 00:13 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-01-20 00:12 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-01-21 00:13 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-01-22 00:11 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-01-23 00:13 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-01-24 00:14 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-01-25 00:15 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-01-26 00:16 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-01-26 08:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-01-27 00:12 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-01-28 00:12 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-01-29 00:12 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-01-29 08:36 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-01-29 10:20 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-01-29 13:10 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-01-29 15:57 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-01-30 00:12 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-01-30 15:34 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-01-31 00:12 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-02-01 00:15 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-02-02 00:17 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-02-03 00:18 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-02-04 00:19 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-02-05 00:19 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-02-06 00:12 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-02-07 00:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-02-08 00:17 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-02-09 00:11 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3612-eiprelklquvjtpmakrhzkwkiyk3fj2tj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b50b1382826646cab3a6c

2024-02-09 15:25 UTC, ribel approved these changes
Changes were tested and cache invalidation now works correct (both for Normal teaser and Featured).
Note that ongoing label is not show for anonymous user, but it was the case already before this change and should be tackled in separate issue and PR.


![image](https://github.com/goalgorilla/open_social/assets/2241917/31db2db9-28f2-4201-afba-ee3a74233c99)

![image](https://github.com/goalgorilla/open_social/assets/2241917/05d4a818-3476-4b5c-a59e-f73580878c68)

![image](https://github.com/goalgorilla/open_social/assets/2241917/19ed3d72-216e-4c20-850b-38a81cc28473)

![image](https://github.com/goalgorilla/open_social/assets/2241917/58851392-224e-4db7-b0d8-dc55c852fd33)

2024-02-09 15:31 UTC, merged

2024-02-09 15:33 UTC, ribel commented
🍒 picked to the 12.2.x and 12.1.x branch