Issue #3325945: Uninstall CTools module
goalgorilla/open_social pull request #3676
Opened 2024-01-03 14:26 UTC by vcsvinicius

## Problem
We added ctools as a dependency in https://github.com/goalgorilla/open_social/pull/1238 However from what I can find we don't actually use the module ourselves. We've only kept it up to date over the years and seemingly locked its version to ensure it didn't change due to pathauto's broader allowed range.

In [#3222775: Remove dependency on CTools](https://www.drupal.org/project/pathauto/issues/3222775) pathauto removed their own dependency on ctools and from what I can find that means we no longer need the dependency.

## Solution
Follow pathauto's playbook and deprecate ctools in a minor version so that we can remove it from composer in a major version.

## Issue tracker
[PROD-27886](https://getopensocial.atlassian.net/browse/PROD-27886)
[#3325945](https://www.drupal.org/project/social/issues/3325945)

## Theme issue tracker
N/A

## How to test
N/A

## Definition of done
### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
The CTools was being used by Path Auto module and they removed the dependency with CTools.
Looking to lowering  the libraries dependency we will remove the CTools from our library.

## Change Record
N/A

## Translations
N/A

2024-01-03 14:28 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3676-0amidhv2kmcymocqb26hkce8ms7t5xfr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65956e8cecd18dd88705342a

2024-01-04 15:13 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3676-0amidhv2kmcymocqb26hkce8ms7t5xfr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65956e8cecd18dd88705342a

2024-01-05 00:24 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3676-0amidhv2kmcymocqb26hkce8ms7t5xfr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65956e8cecd18dd88705342a

2024-01-05 13:48 UTC, robertragas requested changes
There are some inconsistenties in using " and '
Also the update hook isn't really working with the requiredby because right now we are getting dependencies that are requiring ctools, but we don't use them. So it's will never be uninstalled.
![Screenshot 2024-01-05 at 14 41 24](https://github.com/goalgorilla/open_social/assets/19951171/cd4bd97b-0bd8-4187-9b13-56864bbac0eb)

2024-01-07 00:18 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3676-0amidhv2kmcymocqb26hkce8ms7t5xfr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65956e8cecd18dd88705342a

2024-01-08 00:19 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3676-0amidhv2kmcymocqb26hkce8ms7t5xfr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65956e8cecd18dd88705342a

2024-01-08 17:36 UTC, closed without merging