Issue #3418930: Replace user_role_names() deprecated function
goalgorilla/open_social pull request #3742
Opened 2024-02-02 15:49 UTC by vcsvinicius

## Problem
In Drupal 10.2 the system_time_zones() function was deprecated to be removed on Drupal 11.
https://www.drupal.org/node/3349759

## Solution
Replace the deprecated function, get example at: https://www.drupal.org/node/3349759

## Issue tracker
[PROD-28013](https://getopensocial.atlassian.net/browse/PROD-28013)
[#3418930](https://www.drupal.org/project/social/issues/3418930)

## Theme issue tracker
N/A

## How to test
N/A

## Definition of done
### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
N/A

## Change Record
N/A

## Translations
N/A

2024-02-02 15:51 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3742-65zxllnsmxtjhctd0x5m1fwvooeeycbq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bd0f030be493272e5e98c1

2024-02-02 15:55 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3742-65zxllnsmxtjhctd0x5m1fwvooeeycbq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bd0f030be493272e5e98c1

2024-02-02 16:56 UTC, nkoporec requested changes

2024-02-02 16:56 UTC, nkoporec commented on modules/social_features/social_follow_user/src/Form/SocialFollowUserSettingsForm.php
> +      $entity_roles = array_filter(Role::loadMultiple(), fn(RoleInterface $role) => $role->hasPermission($permission));
Can you use dependency injection instead of using the entity directly ? Eg. $this->entityTypeManager->getStorage('user_role')->loadMultiple()

2024-02-03 00:26 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3742-65zxllnsmxtjhctd0x5m1fwvooeeycbq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bd0f030be493272e5e98c1

2024-02-04 00:26 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3742-65zxllnsmxtjhctd0x5m1fwvooeeycbq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bd0f030be493272e5e98c1

2024-02-05 00:26 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3742-65zxllnsmxtjhctd0x5m1fwvooeeycbq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bd0f030be493272e5e98c1

2024-02-05 12:42 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3742-65zxllnsmxtjhctd0x5m1fwvooeeycbq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bd0f030be493272e5e98c1

2024-02-05 12:49 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3742-65zxllnsmxtjhctd0x5m1fwvooeeycbq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bd0f030be493272e5e98c1

2024-02-05 16:17 UTC, nkoporec requested changes

2024-02-05 16:17 UTC, nkoporec commented on modules/social_features/social_follow_user/src/Form/SocialFollowUserSettingsForm.php
> +   * Constructs a \Drupal\system\ConfigFormBase object.
Can you update this to match the correct name.

2024-02-05 16:17 UTC, nkoporec commented on modules/social_features/social_follow_user/src/Form/SocialFollowUserSettingsForm.php
> +  public static function create(ContainerInterface $container): ConfigFormBase|SocialFollowUserSettingsForm|static {
I think we can just return :self here.

2024-02-06 00:21 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3742-65zxllnsmxtjhctd0x5m1fwvooeeycbq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bd0f030be493272e5e98c1

2024-02-07 00:19 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3742-65zxllnsmxtjhctd0x5m1fwvooeeycbq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bd0f030be493272e5e98c1

2024-02-07 14:34 UTC, nkoporec approved these changes

2024-02-08 00:23 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3742-65zxllnsmxtjhctd0x5m1fwvooeeycbq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bd0f030be493272e5e98c1

2024-02-09 00:25 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3742-65zxllnsmxtjhctd0x5m1fwvooeeycbq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bd0f030be493272e5e98c1

2024-02-10 00:23 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3742-65zxllnsmxtjhctd0x5m1fwvooeeycbq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bd0f030be493272e5e98c1

2024-02-11 00:22 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3742-65zxllnsmxtjhctd0x5m1fwvooeeycbq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bd0f030be493272e5e98c1

2024-02-12 00:25 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3742-65zxllnsmxtjhctd0x5m1fwvooeeycbq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bd0f030be493272e5e98c1

2024-02-13 14:31 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3742-65zxllnsmxtjhctd0x5m1fwvooeeycbq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bd0f030be493272e5e98c1

2024-02-13 15:12 UTC, merged

2024-02-13 15:14 UTC, vcsvinicius commented
I cherry-picked to 12.2.x branch