Issue #3436013: Fix sidebar blocks display in flexible groups
goalgorilla/open_social pull request #3833
Opened 2024-03-27 18:50 UTC by tregismoreira

## Problem

We received a bug report saying that some of our clients using the version <code>12.2.1</code> can't see the sidebar blocks "Upcoming events" and "Newest topics" in flexible groups.

As a result of a extensive investigation, we discovered that the issue is caused by 3 misconfigurations:

1. The visibility settings in the block is restricting it to some group types;
2. The contextual filter in the View has a validation criteria restricting the query to some group types;
3. The `social_course` module is [overriding some of the Views configs](https://git.drupalcode.org/project/social_course/-/blob/5.1.x/src/SocialCourseOverrides.php) affecting the query for those blocks.

We also discovered that this issue does not happen to fresh installations.

## Solution

Since the config overriding (3rd item mentioned above) is already been taken care on another issue ([#3416433](https://www.drupal.org/project/social_course/issues/3416433)), we should write an update script to reset the other two configs: **_block visibility settings_**, and **_contextual filter validation criteria_**, so they will match with the install config state. 

We should also write a Behat test to make sure the blocks appears properly in the flexible group sidebar region.

## Issue tracker
https://www.drupal.org/project/social/issues/3436013

## Theme issue tracker
N/A

## How to test
Run the Behat test `tests/behat/features/capabilities/groups/flexible/groups-flexible-sidebar-blocks.feature`

<img width="1246" alt="image" src="https://github.com/goalgorilla/open_social/assets/197236/6eb1ba4c-f815-42fa-871b-f1159e828835">

## Definition of done
### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots

## Release notes

## Change Record

## Translations

2024-03-27 18:50 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-03-28 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-03-29 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-03-30 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-03-31 03:06 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-04-01 03:06 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-04-02 03:06 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-04-03 03:06 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-04-04 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-04-05 03:06 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-04-06 03:45 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-04-07 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-04-08 04:36 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-04-09 04:01 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-04-09 09:00 UTC, ribel requested changes
Hi @tregismoreira,
Changes look good to me on a clean test env, but I still see an issue on old projects.
I will put more details in a ticket.
Also please rename hook update numbers, since we plan to release it in version 12.2.x.

2024-04-09 09:00 UTC, ribel commented on modules/social_features/social_topic/social_topic.install
> +function social_topic_update_120003(): string {
Since we plan to release it in version 12.2.x it's better to rename the hook update number to the `_122001`

2024-04-09 09:00 UTC, ribel commented on modules/social_features/social_event/social_event.install
> +function social_event_update_121003(): string {
Since we plan to release it in version 12.2.x it's better to rename the hook update number to the `_122001`

2024-04-09 15:57 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-04-09 15:57 UTC, tregismoreira commented
@ribel your comments are done, and the commits are cleaned.

2024-04-10 04:39 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-04-10 13:04 UTC, ribel approved these changes
Update hooks were tested and configs are as expected.

2024-04-12 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-04-13 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-04-14 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-04-15 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-04-16 03:06 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-04-17 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-04-18 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-04-19 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-04-20 03:06 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-04-21 03:06 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-04-22 03:06 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-04-23 03:06 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-04-24 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-04-25 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-04-26 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-04-27 03:06 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-04-29 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-05-01 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-05-02 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-05-03 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-05-04 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-05-05 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-05-06 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-05-08 03:06 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-05-09 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-ehjojjr5whn6mtzibsuimejgnxdnecve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66046a6703d41234794e7ffe

2024-05-09 09:39 UTC, ribel commented
Since these changes depends on version 13.0.0 I have changed milestone and update hooks to `13000x`

2024-05-09 09:47 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-fj1petdvkv2yzvxxeuweu6tuknt12t5z.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/663c9a6cbf7868a5631824e4

2024-05-09 09:53 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-fj1petdvkv2yzvxxeuweu6tuknt12t5z.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/663c9a6cbf7868a5631824e4

2024-05-09 10:13 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3833-fj1petdvkv2yzvxxeuweu6tuknt12t5z.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/663c9a6cbf7868a5631824e4

2024-05-09 11:30 UTC, merged