Issue #3453509: Remove hook_insert in social_group_request module, an…
goalgorilla/open_social pull request #3923
Opened 2024-06-09 17:29 UTC by Kovalskiy266

…d place config in optional

We should remove social_group_request_group_content_type_insert hook, because:
 1. This hook is incorrect since it creates the field without entity_type and field_name, which leads to problems with kernel tests
 2. We don't want to create this field for each group_content type

So, we put field_request_message into optional folder where it needed. So, we have list of these modules, which have own group type:
 1. social_discussion_group - has own group type, but doesn't have group_membership_request plugin, which means we don't need to put field_request_message field
2. social_course_advanced_request - has social_group_request module in depedencies and field config in /install
3. social_course_basic_request - has social_group_request module in depedencies and field config in /install
4. social_discussion_secret_group - has own group type, but doesn't have group_membership_request plugin, which means we don't need to put field_request_message field
5. social_flexible_group - put field in /optional, since this module doesn't have social_group_request in depedencies

## Problem

## Solution

## Issue tracker

## Theme issue tracker

## How to test

## Screenshots

## Release notes

## Change Record

## Translations

2024-06-09 17:30 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-06-10 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-06-10 07:54 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-06-11 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-06-12 03:09 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-06-12 18:20 UTC, nkoporec requested changes
I do see an issue here, the current implementation is making sure that each new group type has the field_grequest_message field, the field is then used is GroupRequestMembershipRequestForm. 

With your change we cannot longer assume that this field exists, the field would need to be created by the user when creating the new group type. There are also other implementations referencing this field , for example SocialGroupRequestConfigOverride. So we cannot just remove the hook without at least adding checks to classes mentioned above to check if the field is present in the group type.

For me the current implementation, makes sense, the module relies on field being there so it basically enforce it via hook. If entity_type and field_name are missing can't we just add that instead of removing the hook ?  If only the tests are the issue then for me this is an indication that something is missing in the tests it self or the error is in the test.

2024-06-12 21:52 UTC, Kovalskiy266 commented
Hi, @nkoporec 
Thanks for the review!

| _With your change we cannot longer assume that this field exists, the field would need to be created by the user when creating the new group type_
Yeah, so, when the new `group_type` is created, and we want to enable the `membership request` plugin for this, we should add the field manually for this `group_type`

|  If entity_type and field_name are missing can't we just add that instead of removing the hook ?
Yeah, that makes a sense :)

| _If only the tests are the issue then for me this is an indication that something is missing in the tests it self or the error is in the test._
In tests we should install the s`ocial_group_request` module, when I enable this module in tests I have errors related to `entity_type` and `field_name `, so the problem not in test itself

Discussion in slack about it https://opensocial.slack.com/archives/C0RQ56PFX/p1717575097345489

2024-06-13 04:01 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-06-13 08:14 UTC, Kingdutch commented
I slightly reframed the problem statement in the PR (we likely want to update the Drupal.org issue to match). I hope this change in problem statement shows why removing the hook itself is the correct way forward.

Nejc is right that if we have other pieces of code that reference this field, then removing the hook is not _enough_ to make this work.

`GroupMembershipRequestForm` expects the field to be always there, this is a problem because we're creating a situation where that may not be the case.. We ran into this form before and concluded that it should really be using a proper Content Entity Form so that it can get its fields from the form display configuration. If we were to make that change then that would remove the dependency of that form on this field. That's a change we can make in a separate PR (since it's a change that should work on its own) but it likely would be needed before this PR is merged.

The other place where this field is referenced in the distribution is `SocialGroupRequestConfigOverride`. We know from past experiences that config overrides cause us a lot of pain (although they were needed when we were still using the `features` module). We now have different tools such as the `config_optional` module which allows us to install partial config objects where needed. To be able to remove this hook we would likely need to convert that config override to YML files as well. I believe we can do this in a standalone PR as well to remove that override and make it proper config management. We may run into the same issue of ordering we had in our test in which case we'd need to merge it into this PR instead.

It's unfortunate that we're running into some scope creep here. However, I think the underlying issue is tech debt that we're now encountering for at least a second time. So I also think that that, combined with the path of tackling them in clearly scoped PRs, is a good reason to clean up the tech debt now and not push it forward any longer.

(As a bonus, if we fix the form in `social_group_request` we're likely to be able to replace a custom customer form in a follow-up)

2024-06-14 03:09 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-06-15 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-06-16 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-06-17 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-06-18 03:09 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-06-19 03:09 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-06-20 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-06-21 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-06-22 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-06-23 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-06-24 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-06-25 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-06-26 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-06-27 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-06-28 03:09 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-06-29 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-06-30 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-07-01 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-07-02 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-07-03 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-07-03 11:18 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-07-04 03:06 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-07-05 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-07-06 03:06 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-07-07 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-07-08 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-07-09 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-07-10 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-07-11 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-07-12 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-07-13 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-07-14 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2024-07-15 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3923-zrblzeylxwldku2bbinpgulzcfwdyy71.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6665e6653477de769b5708d4

2025-01-06 13:50 UTC, Kingdutch commented
This pull request has been moved to `migrate/feature/3453509-remove-insert-hook-and-place-config-in-optional` in Cable Car. You can re-open the pull request there using: https://github.com/goalgorilla/cablecar/pull/new/migrate/feature/3453509-remove-insert-hook-and-place-config-in-optional

2025-01-06 13:50 UTC, closed without merging