Issue #3458854: Fix url in getRelatedEntityUrl if entity doesn't have…
goalgorilla/open_social pull request #3963
Opened 2024-07-03 17:15 UTC by Kovalskiy266

… canonical link template

Sometimes the entity related to the activity does not have a canonical URL, which causes a fatal error when viewing the activity.

This error occurs because there is no check to see if the entity has a canonical LinkTemplate.

So, we need to add  a condition to check if entity hasLinkTemplate canonical

## Problem

## Solution

## Issue tracker

## Theme issue tracker

## How to test

## Screenshots

## Release notes

## Change Record

## Translations

2024-07-03 17:16 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-07-04 03:11 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-07-05 03:11 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-07-06 03:10 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-07-07 03:11 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-07-08 03:11 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-07-09 03:10 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-07-09 12:04 UTC, tbsiqueira approved these changes

2024-07-10 03:10 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-07-11 03:10 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-07-12 03:10 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-07-13 03:10 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-07-14 03:10 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-07-15 03:10 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-07-16 03:09 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-07-16 08:27 UTC, ribel approved these changes

2024-07-16 08:42 UTC, Kingdutch requested changes
We're changing something quite fundamental in how our notification system works so this will need more documentation to clearly explain the intent.

The cause for this PR was one of our own entities that we created for which we send notifications that did not have a canonical URL. We've changed our internal implementation to use a different entity that does have it's own display.

In the original code the notification system assumes that a canonical URL exists because it's used to provide a link for a user to follow when they interact with a notification (i.e. "After seeing a notification I can go to the relevant content to interact with it").

The proposed code creates scenario's where that link is no longer available. However, the PR doesn't sufficiently describe what the expected behaviour is in that case.

-----------

To make a decision of whether to merge this PR or to close it as "Won't Fix" we should decide: How do we expect users to interact with notifications that do not have a link?

Once we decide on that expected interaction we should decide whether that's something we want or whether we prefer the UX for the current behaviour (requiring a canonical URL).

If we decide we want the new behaviour we should update the PR to document the things discussed above, if we prefer the old behaviour we can close this PR as won't fix.

2024-07-17 03:09 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-07-18 03:09 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-07-19 03:09 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-07-20 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-07-21 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-07-22 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-07-23 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-07-24 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-07-25 03:09 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-07-26 03:09 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-07-27 03:09 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-07-28 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-07-29 03:09 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-07-30 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-07-31 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-08-01 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-08-02 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-08-03 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-08-04 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-08-05 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-08-06 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-08-07 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-08-08 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-08-09 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-08-10 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-08-11 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-08-12 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-08-13 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-08-14 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-08-16 12:44 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-08-17 03:09 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-08-18 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-08-19 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-08-20 03:10 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-08-21 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-08-22 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-08-23 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-08-24 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-08-26 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-08-27 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-08-28 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-08-29 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-08-30 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-08-31 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-09-01 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-09-02 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-09-03 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-09-04 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-09-05 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-09-06 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-09-07 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-09-08 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-09-09 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-09-10 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-09-11 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-09-12 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-09-13 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-09-14 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-09-15 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-09-16 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-09-17 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-09-18 03:09 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-09-19 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-09-20 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-09-21 03:09 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-09-22 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-09-23 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-09-24 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-09-25 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-09-26 03:10 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-09-28 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-09-30 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-09-30 15:28 UTC, Kovalskiy266 commented
@Kingdutch Hi!

Currently, if the entity that belongs to the activity does not have a `canonical URL`, then we have a fatal error when going to the `notification center`. This change is focused on fixing the error. If we talk about where the notification should redirect to if the entity does not have a canonical URL, then we can handle this on `hook_preprocess_activity` by changing the `full_url` change, this has already been done in many places. Here we don't change func, just prevent fatal error

2024-10-01 03:09 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-10-02 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-10-03 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-10-04 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-10-05 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-10-06 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-10-07 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-10-08 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-10-09 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-10-10 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-10-11 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-10-12 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-10-13 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-10-14 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-10-15 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-10-16 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-10-17 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-10-18 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-10-19 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-10-20 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-10-21 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-10-22 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-10-23 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-10-24 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-10-25 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-10-26 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-10-27 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-10-28 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-10-29 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-10-30 03:09 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-10-31 03:09 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-11-01 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-11-02 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-11-03 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-11-04 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-11-05 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-11-06 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-11-07 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-11-08 03:09 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-11-09 03:07 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-11-10 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-11-11 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-11-12 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-11-13 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-11-14 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-11-15 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-11-16 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-11-17 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2024-11-18 03:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3963-zhhssnkpezancl1t6elu1aogm828jbpf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6685874c1bd6ecfe43426a37

2025-01-02 11:14 UTC, Kingdutch commented
This PR has moved to Cable Car: https://github.com/goalgorilla/cablecar/pull/2571

2025-01-02 11:14 UTC, closed without merging