PROD-30975: Implement "user logs out" event for the EDA
goalgorilla/open_social pull request #4152
Opened 2024-10-31 13:25 UTC by tregismoreira

> [!CAUTION]
> This PR depends on #4151

## Description
This pull request introduces the new EDA event "user logs out" which is dispatches to the Kafka topic `com.getopensocial.cms.user.logout`.

Here's an example of the generated payload:

```
{
	"specversion": "1.0",
	"id": "0cf6cf17-ca0e-4bdd-b791-b3c77a34d300",
	"source": "/user/logout",
	"type": "com.getopensocial.cms.user.logout",
	"datacontenttype": "application/json",
	"time": "2024-10-24T12:15:59Z",
	"data": {
		"user": {
			"id": "3cd53a66-b86a-41b4-8225-66eed5bb5fe3",
			"created": "2024-10-24T12:15:59",
			"updated": "2024-10-24T12:15:59",
			"status": "active",
			"displayName": "admin",
			"firstName": "",
			"lastName": "",
			"email": "devel@getopensocial.com",
			"roles": [
				"authenticated",
				"administrator"
			],
			"timezone": "UTC",
			"language": "en",
			"address": {
				"label": "",
				"countryCode": "",
				"administrativeArea": "",
				"locality": "",
				"dependentLocality": "",
				"postalCode": "",
				"sortingCode": "",
				"addressLine1": "",
				"addressLine2": ""
			},
			"phone": "",
			"function": "",
			"organization": "",
			"href": {
				"canonical": "http://cablecar.localhost/user/1/home"
			}
		},
		"actor": {
			"application": null,
			"user": {
				"id": "3cd53a66-b86a-41b4-8225-66eed5bb5fe3",
				"displayName": "admin",
				"href": {
					"canonical": "http://cablecar.localhost/user/1/home"
				}
			}
		}
	}
}
```

## Release notes (to customers)
N/A

## Issue tracker
https://getopensocial.atlassian.net/browse/PROD-30975

## Theme issue tracker
N/A

## How to test
- [ ] Checkout branch `issue/PROD-30974-eda-user-login`
- [ ] Enable modules `social_eda` and `social_eda_dispatcher`
- [ ] Log in as any user

The message should be dispatched to Kafka. If you are running locally using the Docker containers, you should be able to see the message on the Kafka UI at http://localhost:8080/.

## Change Record

## Translations

2024-10-31 13:31 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4152-zx0kog9m594jybd6tvvrdzqp2ighyfnm.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6723853e6ec433609ae8aa99

2024-10-31 14:32 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4152-zx0kog9m594jybd6tvvrdzqp2ighyfnm.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6723853e6ec433609ae8aa99

2024-11-01 07:56 UTC, bramtenhove requested changes
I noticed the payload data contains more than was designed for.

2024-11-01 07:56 UTC, bramtenhove commented on modules/social_features/social_user/asyncapi.yml
> +                      description: The email address of the user.
```suggestion
```

As part of the payload design we left this out.

2024-11-01 07:56 UTC, bramtenhove commented on modules/social_features/social_user/asyncapi.yml
> +                      description: The organization of the user.
```suggestion
```

As part of the payload design we left this out.

2024-11-01 15:51 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4152-zx0kog9m594jybd6tvvrdzqp2ighyfnm.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6723853e6ec433609ae8aa99

2024-11-01 16:01 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4152-zx0kog9m594jybd6tvvrdzqp2ighyfnm.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6723853e6ec433609ae8aa99

2024-11-04 14:27 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4152-zx0kog9m594jybd6tvvrdzqp2ighyfnm.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6723853e6ec433609ae8aa99

2024-11-04 15:08 UTC, open-social-tugboat commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4152-zx0kog9m594jybd6tvvrdzqp2ighyfnm.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6723853e6ec433609ae8aa99

2024-11-05 14:42 UTC, ribel approved these changes
Changes were tested and works as expected.

2024-11-05 14:42 UTC, merged